### ISSUE TITLE
Receive-WinSCPItem / Send-WinSCPItem  -Remove

### ISSUE THREAD

**Issue by ratoka** [dotps1/WinSCP#10]
There doesn't seem to be a way to use the -Remove tag without deleting the folder.  Optimally we would be able to remove just the downloaded files, leaving the folder intact.

**Comment by dotps1** [comment]
You would have to do a ForEach-Object Receive-WinSCPItem -Remove. and do each item, if you just use Receive-WinSCPItem '/Directory' -Remove, it will remove that directory.

```PowerShell
$s = Open-WinSCPSession -SessionOptions (New-WinSCPSessionOptions -HostName 'host' -UserName 'user' -Protocol Ftp)

Get-WinSCPDirectoryContents -WinSCPSession $session | ForEach-Object {
     Receive-WinSCPSession -WinSCPSession $session -RemoteItem $_ -Remove
}
```

Something like that should work.

**Comment by dotps1** [comment]
Closing issue, no reply.

**Comment by ratoka** [comment]
I was able to work around with a loop.  Intuitively though, -remove would only remove what was downloaded/uploaded.

**Comment by dotps1** [comment]
That is what is happening, if you specify a folder with the -remove tag, after it downloads that folder, and its contents, it will remove the folder.

**Comment by ratoka** [comment]
That makes sense.  My confusion is that in the actual downloaded files, the folder is not included, just the contained files/folders.
