### ISSUE TITLE
Fallen at first hurdle

### ISSUE THREAD

**Issue by action711** [dotps1/WinSCP#103]
_Please fill in the following fields, replacing the values inside the brackets `{{ }}`._

### Issue Description

{{ Installed it, but get errors on basic commands }}

### Example

{{ I've installed it and am trying out basic commands, but just can't get anywhere at all

	$sessionOption = New-WinSCPSessionOption -HostName website.com or New-WinSCPSessionOption -HostName website.com
 }}

### Expected Output

{{ Don't know, haven't used it before }}

### Actual Output

{{ Method invocation failed because [System.Security.SecureString] does not contain a method named 'new'.
At line:1 char:1
+ $sessionOption = New-WinSCPSessionOption -HostName SFTPData-prod.checkprint.co.u ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound }}

### WinSCP-PowerShell Version

{{ 5.15.1.0 }}\

### Environment

{{ Name             : ConsoleHost
Version          : 4.0
InstanceId       : 1cf56fdf-3adb-4016-ac40-04a44055860b
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-GB
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
               }}

**Comment by jeffreymcclain** [comment]
First try the easiest step of rebooting if you haven't already done so ;)

Assuming that doesn't work, run "Get-InstalledModule" and see if the WinSCP module is listed and if it's the latest version. If not, run PowerShell as administrator and run the command "Install-Module -Name WinSCP". Close and reopen the PowerShell window, and possibly reboot to be on the safe side.

What OS are you using? Try updating to PowerShell 5.1 Desktop edition. 
- https://docs.microsoft.com/en-us/powershell/scripting/install/installing-windows-powershell?view=powershell-5.1#upgrading-existing-windows-powershell

- use "$PSVersionTable.PSVersion" and "$PSVersionTable.PSEdition" to validate.

I just tested by running 

`$sessionOption = New-WinSCPSessionOption -HostName "google.com"`

with no errors, so it's definitely just an issue with your environment.

**Comment by dotps1** [comment]
It does sound like your environment is quite dated.  Perhaps ill up the minimum required version of PowerShell to v5.  v4 is very dated.  Basically, when you use the `New-WinSCPSessionOption` with no `-Credential` parameter value, it creates a default credetinal.  And there is no method for `[System.Security.SecureString]::new()`.

but you really should think about updating your PowerShell version.  I mean v7 is upon us.

**Comment by dotps1** [comment]
Im going to go ahead and close this as of lack of response.
