### ISSUE TITLE
Turn off or ignore permission options 

### ISSUE THREAD

**Issue by lostmojos** [dotps1/WinSCP#104]
### Issue Description

Unable to stop setting permission or timestamps while sending.  Server is reporting the error "Send-WinSCPItem : WinSCP.SessionRemoteException: **Upload of file 'Substitution_20190517_1136.txt' was successful, but 
error occurred while setting the permissions and/or timestamp.**"

### Example

New-WinSCPTransferOption -ResumeSupport (New-WinSCPTransferResumeSupport -State off) -TransferMode ascii -PreserveTimestamp $false
and 
New-WinSCPTransferOption -ResumeSupport (New-WinSCPTransferResumeSupport -State off) -TransferMode ascii -PreserveTimestamp:$false

### Expected Output

Successful file send

### Actual Output

+ ... endResult = Send-WinSCPItem -WinSCPSession $WinSCPSession -LocalPath  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Send-WinSCPItem

Send-WinSCPItem : WinSCP.SessionRemoteException: **Upload of file 'Substitution_20190517_1136.txt' was successful, but 
error occurred while setting the permissions and/or timestamp.**

If the problem persists, turn off setting permissions or preserving timestamp. Alternatively you can turn on 'Ignore 
permission errors' option.
Permission denied.
Error code: 3
Error message from server: File attributes may not be changed for /home/ERP/Feed/Substitution_20190517_1136.txt

### WinSCP-PowerShell Version

Script     5.13.9.1   winscp

### Environment

Windows server 2019, server is sftp

**Comment by dotps1** [comment]
I have to ask, you are using the transferoptions in the `Send-WinSCPItem` command correct?
```powershell
$to = New-WinSCPTransferOptions -PreserveTimeStamp $false
Send-WinSCPItem -TransferOptions $to -Path .\file.txt -Destination './folder/'
```
I just don't see it in your "actual output" example

the object is defiantly being created correctly:
```
PS C:\GitHub\WinSCP> New-WinSCPTransferOption


PreserveTimestamp : True
FilePermissions   :
TransferMode      : Binary
FileMask          :
ResumeSupport     : default
SpeedLimit        : 0
OverwriteMode     : Overwrite



PS C:\GitHub\WinSCP> New-WinSCPTransferOption -PreserveTimestamp $false


PreserveTimestamp : False
FilePermissions   :
TransferMode      : Binary
FileMask          :
ResumeSupport     : default
SpeedLimit        : 0
OverwriteMode     : Overwrite
```

This did however bring something else to my attention, which is proper naming context should be `TransferOption` not `TransferOptions`.

**Comment by dotps1** [comment]
Closing, no response, feel free to reopen.
