### ISSUE TITLE
Some parameters have placeholder text in the description field

### ISSUE THREAD

**Issue by jeffreymcclain** [dotps1/WinSCP#105]
### Issue Description

I was browsing the Wiki and noticed that several parameters have placeholder text in the description field.

### Example

Get-WinSCPItem, Filter: @{Text=}
New-WinSCPSessionOption, SecurePrivateKeyPassphrase: {{Fill SecurePrivateKeyPassphrase Description}}
New-WinSCPTransferOption, FileMask: @{Text=}
New-WinSCPTransferOption, ResumeSupport: {{ Fill ResumeSupport Description }}
New-WinSCPTransferResumeSupport, State: {{Fill State Description}}

### Expected Output

There should be actual descriptions, not placeholder text.

**Comment by jeffreymcclain** [comment]
@dotps1 This issue is back, perhaps the changes did not carry over when you updated the build to 5.15.3 ?

**Comment by tomohulk** [comment]
should be good now.

**Comment by jeffreymcclain** [comment]
Thanks @tomohulk , btw I also submitted a pull request with a few other minor fixes.
