### ISSUE TITLE
Does this module support the Linux version of powershell?

### ISSUE THREAD

**Issue by chuanjiao10** [dotps1/WinSCP#106]
### Does this module support the Linux version of powershell?

 What version of powershell is supported?
i have seen https://winscp.net/tracker/1640 , it say:supported NET Core by 5.14 . 
Is it mean ,only support windows version of .net core? 

### Example

import-module winscp

### Actual Output

```
PS /root> import-module winscp
import-module : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At line:1 char:1
+ import-module winscp
+ ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
+ FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

```

### WinSCP-PowerShell Version

v5.15.2.0

### Environment
centos7.6 + ps v6.0.5
centos7.6 + ps v6.1.5
centos7.6 + ps v6.2.2

**Comment by dotps1** [comment]
I am not really sure, and i have no reason to have ever tried it.  I mean most of this functionality already lives in linux, so im not really sure a reason to run WinSCP on linux.

To answer the actual question, its test with PowerShell v5.

**Comment by martinprikryl** [comment]
The module runs `WinSCP.exe` internally. What is a Windows application. So it can hardly work on Linux.

**Comment by chuanjiao10** [comment]
en ,i tested.it can not run on linux + powershell core.this is very regrettable.
I want to use winscp to copy files and execute powershell commands in linux2linux,
Looking forward to winscp can support Linux as soon as possible.

**Comment by dotps1** [comment]
I wouldn't be too hopeful on this.  i mean in linux, `scp` exists nativity, so to spend the time to port a windows application to linux to do what linux can already do, is frankly, a waste of time.  and you can literally use the `scp` command from the powershell engine on linux by just running `scp`.  I have tested this on macOS:

<img width="697" alt="Screen Shot 2019-08-08 at 8 30 25 AM" src="https://user-images.githubusercontent.com/1016996/62703274-d3cb1900-b9b6-11e9-9104-745a0f124981.png">

**Comment by chuanjiao10** [comment]
1 I am not a beginner, I am a developer. I want to develop an automatic operation and maintenance tool. Similar to ansible.
https://github.com/chuanjiao10/kasini3000/wiki/%E5%8D%A1%E6%AD%BB%E4%BD%A03000%E4%BD%BF%E7%94%A8%E5%9C%BA %E6%99%AF

2 Maybe you still don't realize that winscp is so good!
2.1 scp requires the server, the client needs to both installed.
2.2 ssh user@ip ‘command’ is very inconvenient and cannot be scripted.
2.3 new-pssession supports linux to linux, but requires manual password input, can not adapt to automatic operation and maintenance tools.
2.4 winscp does not support from linux to linux.

**Comment by martinprikryl** [comment]
I do not understand your point 2.1

**Comment by chuanjiao10** [comment]
scp  Source Destination.
Destination linux must  install scp.
in the centos7,it is package 'openssh-clients-7.4p1-16.el7.x86_64'

**Comment by martinprikryl** [comment]
If you use SCP protocol in WinSCP, you also need `scp` on the server. There's no difference.

**Comment by chuanjiao10** [comment]
Send-WinSCPItem Needs scp on Destination Linux too?

**Comment by martinprikryl** [comment]
It does, if you use SCP protocol. You possibly use SFTP protocol in WinSCP. But then you cannot compare WinSCP to `scp`, but to `sftp`. `sftp` does not need `scp` on the server neither.

**Comment by dotps1** [comment]
well, as far as this repo is concerned, if WinSCP is not support on linux, neither is the powershell module.
