### ISSUE TITLE
New-WinSCPSessionOption: SshPrivateKeyPath Parameter Doesn't Escape Network Share Paths Properly

### ISSUE THREAD

**Issue by jeffreymcclain** [dotps1/WinSCP#108]
### Issue Description

Network Share paths in SshPrivateKeyPath Parameter aren't escaped properly.

### Example

$sessionOption = New-WinSCPSessionOption -HostName $sftpHostname -SshPrivateKeyPath 'C:\Temp\test.ppk'
echo $sessionOption

$sessionOption = New-WinSCPSessionOption -HostName $sftpHostname -SshPrivateKeyPath '\\\\cifs01.company.com\EncryptionKeys\test.ppk'
echo $sessionOption

### Expected Output

SshPrivateKeyPath                            : C:\Temp\test.ppk
SshPrivateKeyPath                            : \\\\cifs01.company.com\EncryptionKeys\test.ppk

### Actual Output

SshPrivateKeyPath                            : C:\Temp\test.ppk
SshPrivateKeyPath                            : Microsoft.PowerShell.Core\FileSystem::\\\\cifs01.company.com\EncryptionKeys\test.ppk

When calling New-WinSCPSession with a network path, it fails with:

New-WinSCPSession : Exception calling "Open" with "1" argument(s): "Disconnected: No supported authentication methods available (server sent: publickey)
Authentication log (see session log for details):
Unable to use key file "Microsoft.PowerShell.Core\FileSystem::\\\\cifs01.company.com\EncryptionKeys\test.ppk" (unable to open file)
Using username "test".
Authentication failed."
At C:\Scripts\test.ps1:26 char:12
+ $session = New-WinSCPSession -SessionOption $sessionOption
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-WinSCPSession], MethodInvocationException
    + FullyQualifiedErrorId : SessionRemoteException,New-WinSCPSession

If I leave everything else identical (including username and password), but copy the .ppk file from the network share to the local machine and specify the local path, then New-WinSCPSession connects as expected (so the issue seems to be with how the network share path is handled).

### WinSCP-PowerShell Version

5.15.2.0

### Environment

Windows Server 2016 64-bit, connecting to SFTP server with username, private-key file, and private-key passphrase.

**Comment by dotps1** [comment]
Please give this version a try if can and let me know if it works.  thanks!
[WinSCP.zip](https://github.com/dotps1/WinSCP/files/3478144/WinSCP.zip)

**Comment by jeffreymcclain** [comment]
Once I unzip the folder, how do I manually install / import the module for testing?

**Comment by dotps1** [comment]
Import-Module -Path <PathToPsd1>

Sent from my iPhone

On Aug 8, 2019, at 12:00 PM, Jeffrey McClain <notifications@github.com> wrote:

﻿

Once I unzip the folder, how do I manually install / import the module for testing?

**Comment by jeffreymcclain** [comment]
Just tested and it works!

P.S.:

> Import-Module -Path <PathToPsd1>

For reference, the actual command was "Import-Module -Name <PathToPsd1>".
I also had to Set-ExecutionPolicy to "Unrestricted" and unblock some files after extracting, since they were "downloaded from the internet".
