### ISSUE TITLE
The term 'New-WinSCPSessionOptions' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by Richard-West** [dotps1/WinSCP#11]
Hi,

I've downloaded an installed your plugin through the Install-Module cmdlet. 

When I'm trying to run the code in your Example 1, with my server, user and password  of course, I get a Powershell error:

    New-WinSCPSessionOptions : The term 'New-WinSCPSessionOptions' is not recognized as the name of a cmdlet, function, script 
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and 
try again.

Any ideas on what I might have configured incorrectly on my side, or is there a know problem that causes this error?

**Comment by dotps1** [comment]
Did you import the module?  it is net set up to autoload.
```PowerShell
Import-Module -Name WinSCP
```

**Comment by dotps1** [comment]
Closing, no response.
