### ISSUE TITLE
“#” defeated “Invoke-WinSCPCommand ”

### ISSUE THREAD

**Issue by chuanjiao10** [dotps1/WinSCP#111]
# “#” defeated “Invoke-WinSCPCommand ”
Invoke-WinSCPCommand hang when Comment in command line,
then Invoke-WinSCPCommand will return timeout.

eg:
```
Invoke-WinSCPCommand -WinSCPSession $s -Command "ls #aaa"
```

WinSCP-PowerShell Version
v5.15.2.0

Environment
from win10 + ps v5.1
to centos76

**Comment by dotps1** [comment]
maybe `Escape-WinSCPPath` would work, im not sure.  I don't have a way to test right now, but i will try over the weekend.

**Comment by dotps1** [comment]
closing this because the requester in no way deserves any help.
