### ISSUE TITLE
Request: Add BaseName and Extension Properties for Get-WinSCPItem and Get WinSCPChildItem

### ISSUE THREAD

**Issue by jeffreymcclain** [dotps1/WinSCP#113]
### Issue Description

For items returned from the "Get-WinSCPItem" and "Get WinSCPChildItem" cmdlets, there are only ".Name" and ".FullName" properties. It would be nice if there were ".BaseName" and ".Extension" properties as well, similar to Powershell's builtin "Get-Item" cmdlet.

### Example

https://i.imgur.com/4NPqcmV.png

### WinSCP-PowerShell Version

5.15.3.0

### Environment

Windows 10 64-bit, v1903.

**Comment by dotps1** [comment]
it returns the WinSCP object, i don't build it.  Use `| Select *` to see the available properties.

**Comment by dotps1** [comment]
https://winscp.net/eng/docs/library_remotefileinfo.  And as this is a wrapper, I am not going to manipulate the object returned.
