### ISSUE TITLE
Typos in Get-WinSCPItem and Get-WinSCPChildItem

### ISSUE THREAD

**Issue by jeffreymcclain** [dotps1/WinSCP#114]
### Issue Description

There is a small typo on the Wiki page "Get-WinSCPItem" in the Description.
Specifically, "remote file.s" should be "remote files."

There is also a small typo on the Wiki page "Get-WinSCPChildItem" in Example 2.
Specifically, "Get-WinChildItem" should be "Get-WinSCPChildItem".

### Example

https://github.com/dotps1/WinSCP/wiki/Get-WinSCPItem#description
https://github.com/dotps1/WinSCP/wiki/Get-WinSCPChildItem#example-2

### Notes
P.S.:  I created a pull request to try to help fix this last month and save you some time: https://github.com/dotps1/WinSCP/pull/112

These are relatively trivial / minor fixes, but I figured I'd mention them anyways. Feel free to either use my pull request or fix them a different way.

Thanks again for supporting this module so well, I see you already updated the build to 5.15.4 a few hours ago!

**Comment by dotps1** [comment]
fixed with v5.15.5.

thanks.
