### ISSUE TITLE
It's too irresponsible for your own project. Close it.

### ISSUE THREAD

**Issue by chuanjiao10** [dotps1/WinSCP#117]
_Please fill in the following fields, replacing the values inside the brackets `{{ }}`._

### Issue Description

{{ Please provide a description here. }}

### Example

{{ Please provide an example of the code being used. }}

### Expected Output

{{ Please provide what expect to happen. }}

### Actual Output

{{ Please provide what actually happened. }}

### WinSCP-PowerShell Version

{{ Paste output of `Get-Module -Name WinSCP | Clip` here }}\

### Environment

{{ Please provide OS Information (Version, Arch, etc), PowerShell Version (Output of `$host`) and what FTP flavor the server is. }}

**Comment by dotps1** [comment]
yes sir!  i will do what ever you say just because my FREE PROJECT THAT NO ONE IS MAKING YOU USE is not made the exact way you want it.  Maybe instead of trolling my project, take a little initiative and make your own, and then you can make it however you like.

**Comment by dotps1** [comment]
closing, has nothing to do with the project, requester is just butt hurt because this freeware is not designed the way they'd like, and is either too lazy, or too incompetent to fork and make their own changes.
