### ISSUE TITLE
Who hid what he had just said? He is a coward!

### ISSUE THREAD

**Issue by chuanjiao10** [dotps1/WinSCP#118]
i am not,i never add the "-username" parameter(for New-WinSCPSessionOption).
to users: if you don't like it, don't use it.

Why hide, why not say it out loud to everyone?

**Comment by tomohulk** [comment]
im done with you, im no longer accepting issues for this project, way to ruin it for everyone.

**Comment by dotps1** [comment]
try just looking in the closed issues.  idiot.
