### ISSUE TITLE
PSCore - cannot create new winscp session

### ISSUE THREAD

**Issue by AZ-Vede** [dotps1/WinSCP#120]
### Issue Description

cannot execute "New-WinSCPSession" cmdlet

### Example

```
   [WinSCP.SessionOptions]$SessionOptions = New-WinSCPSessionOption  -Protocol sftp -HostName $ftpServer -Credential $credential -SshHostKeyFingerprint $sshHostKey
   $ftpSession = New-WinSCPSession -SessionOption $SessionOptions
```

### Expected Output

$ftpSession will hold a valid session that I can interact with

### Actual Output

```
New-WinSCPSession : Exception calling "Open" with "1" argument(s): "Method not found: 'Void System.Threading.EventWaitHandle..ctor(Boolean, System.Threading.EventResetMode, System.String, Boolean ByRef, System.Security.AccessControl.EventWaitHandleSecurity)'."
At line:1 char:18
+    $ftpSession = New-WinSCPSession -SessionOption $SessionOptions
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [New-WinSCPSession], MethodInvocationException
+ FullyQualifiedErrorId : MissingMethodException,New-WinSCPSession
```

### WinSCP-PowerShell Version

ModuleType Version    Name 
---------- -------    ----        
Script     5.15.5.0   WinSCP

### Environment

Win10 Pro, build 18362

Name             : ConsoleHost
Version          : 6.2.3
InstanceId       : a19e85d4-a0ed-4ef6-938d-be84828afb92
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

**Comment by AZ-Vede** [comment]
I'd be happy to try this in a non-core powershell version as well, to see if it replicates there, I've just been a bit busy today... probably tonight or tomorrow.

also, the inner exception indicates it's running into the exception in the $session.open( on line 106 of that cmdlet's file.

**Comment by AZ-Vede** [comment]
update: does not replicate in Powershell v5.1.18362.145

**Comment by tomohulk** [comment]
can you try it without casting the `WinSCP.SessionOptions` part?

```PowerShell
$SessionOptions = New-WinSCPSessionOption -Protocol sftp -HostName $ftpServer -Credential $credential -SshHostKeyFingerprint $sshHostKey
$ftpSession = New-WinSCPSession -SessionOption $SessionOptions
```

**Comment by AZ-Vede** [comment]
I first ran it that way; I added the variable type declaration/cast in the process of trying to resolve the issue myself before coming here. No change in the exception at all.

Would it be worthwhile for me to paste up the full content of the thrown exception object? I couldn't see a ton of inner information that was terribly useful, but I was kind of searching blind.

**Comment by MathewCXT** [comment]
I don't know if this helps, but, I am experiencing this same issue with PowerShell 7.

**Comment by martinprikryl** [comment]
The problem is caused by using .NET Framework build of WinSCP .NET assembly in .NET Core. Use .NET Core version of the assembly – I do not know how to do it in the context of the WinSCP PowerShell Wrapper Module though.  @tomohulk may know.

**Comment by MathewCXT** [comment]
Thanks @martinprikryl !

I was able to get this working with PowerShell 7 by downloading the WinSCP .Net Assembly/Com Library (https://winscp.net/eng/downloads.php) and replacing the following files:

.\netstandard2.0\WinSCPnet.dll → C:\Program Files\WindowsPowerShell\Modules\WinSCP\{VERSION}\lib **(OVERWRITE)**

.\WinSCP.exe → C:\Program Files\WindowsPowerShell\Modules\WinSCP\{VERSION}\bin **(OVERWRITE)**

**Comment by AZ-Vede** [comment]
Thanks, that solved it perfectly!
