### ISSUE TITLE
5.17 Released to Stable Channel

### ISSUE THREAD

**Issue by jeffreymcclain** [dotps1/WinSCP#124]
### Issue Description

This is more of a suggestion than an issue, I just wanted to let you know that version 5.17 was released recently (latest stable version is 5.17.2). No rush, but if it's not too much trouble, I was wondering if you plan to update the module from 5.15 to 5.17 in the near future.

Sincerely,

Jeffrey

**Comment by ca6dsm** [comment]
I'm wondering the same

**Comment by tomohulk** [comment]
sorry guys, I switched to a Mac about a year ago, and with PS6 things like ssh/scp are native.  So this module is frankly quite pointless, and not really on my watch list so much anymore.  Anyway, I updated the core components.

**Comment by jeffreymcclain** [comment]
@tomohulk Thanks! For PowerShell 6 (and PowerShell 7 which was recently released to stable), do you know if there is an easy way to pass a credential object and/or save the ssh/sftp session to a variable?

For example, I can ssh to a server using the built-in "ssh" command, but I don't see an easy way of passing a credential parameter. Furthermore, if I try to save the session ($session = ssh ... ) to reuse at other points in my script, it just fails with an error.

**Comment by tomohulk** [comment]
maybe win Invoke-command, but i'm not sure
