### ISSUE TITLE
[Question] Disable session reconnect completely?

### ISSUE THREAD

**Issue by OCram85** [dotps1/WinSCP#128]
Is there a way to disable the auto reconnect feature like within the GUI?

[![image.png](https://i.postimg.cc/ZKJ4DHgB/image.png)](https://postimg.cc/5jKhXBfb)

**Comment by tomohulk** [comment]
I don't have a good way to test this right now, but you can try the `-ReconnectTime` parameter on the `New-WinSCPSession` cmdlet, just set it to 0.

**Comment by OCram85** [comment]
Thanks, I will try it and let you know the results! 😄

**Comment by OCram85** [comment]
So I tried disabling the reconnect with `-ReconnectTime 0` and additionally adding a custom transfer option like this:

```powershell
Send-WinSCPItem @ParamsSendItem -TransferOptions (
  New-WinSCPTransferOption -ResumeSupport (
    New-WinSCPTransferResumeSupport -State Off
  )
)
```

> Unfortunately it doesn't work either 😢

**Comment by tomohulk** [comment]
can you try it on the `WinSCP.Session` object.  Created with `New-WinSCPSession`?  use the `-ReconnectTime` parameter.  the object supports this.

https://winscp.net/eng/docs/library_session (see the ReconnectTime parameter)
>Sets time limit in seconds to try reconnecting broken sessions. Default is 120 seconds. Use TimeSpan.MaxValue to remove any limit. The property has to be set before calling Open.

`New-WinSCPSession -SessionOptions $sessionOptions -ReconnectTime [TimeSpan]::new(0)`

**Comment by schlabbe14** [comment]
these additional configurations could be set by using AddRawConfiguration:

    $ParamsNewWinSCPSessionOption = @{
        Credential = $Credential
        Hostname   = $FTP
        Protocol   = 'Ftp'
        FtpMode    = 'Passive'
        Timeout    = [timespan]::FromMinutes(5)
     }
     $SessionOption = New-WinSCPSessionOption @ParamsNewWinSCPSessionOption
     $WinSCPSession = New-WinSCPSession -SessionOption $SessionOption
     $WinSCPSession.Close()
     $WinSCPSession.AddRawConfiguration('Interface\SessionReopenAuto',0)
     $WinSCPSession.AddRawConfiguration('Interface\SessionReopenIdle',0)
     $WinSCPSession.AddRawConfiguration('Interface\SessionReopenStall',0)
     $WinSCPSession.Open($SessionOption)

**Comment by OCram85** [comment]
@tomohulk: Sorry for the delay!
@schlabbe14 helped me out with this:  It works now with customizing the `RawConfiguration`....

**Comment by schlabbe14** [comment]
jip ;-)
