### ISSUE TITLE
Add support for PowerShell 7 (.NET Core)

### ISSUE THREAD

**Issue by Wardrop** [dotps1/WinSCP#130]
The WinSCP module currently can't be used with PowerShell 7 as it's bundled with _WinSCPnet.dll_ built for .NET Standard. I'm assuming powershell modules can be built to load different assemblies depending on the environment, if so, that would make for a relatively easy fix as _WinSCPnet.dll_ for both .NET Framework and .NET Standard/Core could be bundled and loaded dynamically depending on the environment.

**Comment by doyoucompute** [comment]
I have the same issue. Cannot figure out how/where to get it to use the netstandard2.0 winscpnet.dll.

**Comment by tomohulk** [comment]
I have this implemented,  I need to overhaul my pester tests to get this build working again.  Once I have that complete it will make its way to the powershell gallery, else you can download the code from the repo if you'd like it sooner.

thanks.
