### ISSUE TITLE
How to disable transfer resume support state?

### ISSUE THREAD

**Issue by wshyang** [dotps1/WinSCP#132]
Hi Sir,

This is not so much an issue report per se, but it is not very clear how to create the appropriate TransferResumeSupportState to set transfer resume state to "Off".

I am able to set the state to be default by creating a default object using
`New-Object -type WinSCP.TransferResumeSupportState`

However how can I create a "off" object?

**Comment by tomohulk** [comment]
https://github.com/dotps1/WinSCP/wiki/New-WinSCPTransferResumeSupport

see the `-State` switch

```powershell
New-WinSCPTransferResumeSupport -State Off
```
