### ISSUE TITLE
Updating to v5.19.6

### ISSUE THREAD

**Issue by jlbentley001** [dotps1/WinSCP#138]
Is there any plan to update to the latest version of 5.19.6 and publishing it? Or is this something we can do manually?
I have been using  v5.17.10, but I am needing to update the application. 
On my test machine, I have been playing around with it and have successfully updated the winscp application and then modifying the module files locally to match. So far results have been successful and all sees it running as the latest version.

Thanks in advance for any input.

**Comment by tomohulk** [comment]
AppVeyor seems to be seriously broke, so I am not able to publish to the powershell gallery at this time. but you can grab the module with updated WinSCP core here: https://github.com/dotps1/WinSCP/releases/tag/WinSCP-PowerShell-v5.19.6.0
