### ISSUE TITLE
New:WinSCPSession: bug in $SshPrivateKeyPassphrase parameter

### ISSUE THREAD

**Issue by mpavone** [dotps1/WinSCP#14]
I found out a bug in the management of the parameter $SshPrivateKeyPassphrase

The parameter has been defined as SecureString, see below:

        [Parameter()]
        [ValidateScript({ -not ([String]::IsNullOrWhiteSpace($_)) })]
        [SecureString]
        $SshPrivateKeyPassphrase = $null,

But insider the function code you try to assign to a string (the decoded string) into the same parameter:

$SshPrivateKeyPassphrase = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($SshPrivateKeyPassphrase))

This raises to the following error:

Cannot convert the "*******" value of type "System.String" to type "System.Security.SecureString".

Thank you
Martino

**Comment by dotps1** [comment]
Great find, i have changed the Type of the variable.  I need to keep the Variable Names the same, and not create new variable names because that will break how i enumerate parameter keys/values.

go ahead and grab the latest if you'd like.  Ill wait to hear back before i close this issue.  thanks

Thanks.

**Comment by mpavone** [comment]
I'm so sorry but it is still not working...
When you make the following cast: 
[String]$SshPrivateKeyPassphrase = [System.Runtime......
the parameter remains a SecureSring as defined in the interface.
Moreover, the SessionOptions accept string not SecureString.
I propose to duplicate the parameters in 

        [Parameter()]
        [ValidateScript({ -not ([String]::IsNullOrWhiteSpace($_)) })]
        [SecureString]
        $SecureSshPrivateKeyPassphrase = $null,

        [Parameter()]
        [ValidateScript({ -not ([String]::IsNullOrWhiteSpace($_)) })]
        [String]
        $SshPrivateKeyPassphrase = $null,

If you use SshPrivateKeyPassphrase, the parameter is bound to the SessionOptions (it doesn't need any transformation)
If you use SecureSshPrivateKeyPassphrase, you can assign manually the value

        # Enumerate each parameter.
        foreach ($key in $PSBoundParameters.Keys)
        {
         ...................................................
        }

	if ($SecureSshPrivateKeyPassphrase -ne $null)
	{
			$sessionOptions.SshPrivateKeyPassphrase = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecureSshPrivateKeyPassphrase))
	 } 

I have tested the above approach and it works.
I have also created a fork with the proposed changes
Let me know if you agree with this approach

Martino

**Comment by dotps1** [comment]
I will look into this more.  The reason for the securestring is because PS best practices say all passwords/passphrases need to be of that object type.   thanks for all your feed back, ill let you know.

Sent from my Windows Phone
________________________________

**Comment by mpavone** [comment]
I definitely agree with the best practice.
Another solution is to keep only the $SecureSshPrivateKeyPassphrase and remove the parameter SshPrivateKeyPassphrase

Remove the code below:
    [Parameter()]
    [ValidateScript({ -not ([String]::IsNullOrWhiteSpace($_)) })]
    [String]
    $SshPrivateKeyPassphrase = $null,


In this way, you can only pass secure passphrase.
This should work and it will bypass the security concerns.

Ciao, Martino

**Comment by dotps1** [comment]
im not sure why my orginal fix does not work, i wrote this little test function and it works fine:

```PowerShell
$testString = ConvertTo-SecureString -String 'HereIsMyTestString' -AsPlainText -Force

Function Test-SecureStringCasting ([SecureString]$SecureString)
{
    [String]$SecureString = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecureString))

    return $SecureString
}

Test-SecureStringCasting -SecureString $testString
```

It allows me to recast the same variable name as a different type.  So im a little confused.  I unfortunately don't have an FTP Server at my disposal with a certificate with a password, but i will get that set up.  Thanks.

**Comment by dotps1** [comment]
Ok, i re-read your suggestion again, and i like the parameterName change.  so implemented the following code
```PowerShell
        [Parameter()]
        [ValidateScript({ -not ([String]::IsNullOrWhiteSpace($_)) })]
        [SecureString]
        $SshPrivateKeySecurePassphrase = $null,

#.....

    # Convert SshPrivateKeySecurePasspahrase to plain text and set it to the corresponding SessionOptions property.
    if ($SshPrivateKeySecurePassphrase -ne $null)
    {
        $sessionOptions.SshPrivateKeyPassphrase = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($SshPrivateKeySecurePassphrase))
    }

#......
```

Thanks again!
