### ISSUE TITLE
Export logs 

### ISSUE THREAD

**Issue by Eduardgur** [dotps1/WinSCP#140]
### Issue Description

Cant access logs after sync command, 
Becuase we suffer from some problems with the timestamps ide lile to be able to get a full log to the location set in the script. 

### Example

Cant get full log after running Sync-WinSCPPath

### Expected Output

Ide like to be able to redirect the log to a different location exactly like the winscp switch: /log=

### Actual Output

Only getting the command output

### WinSCP-PowerShell Version

5.17.10.0

### Environment
Running on Windows server 2019

**Comment by tomohulk** [comment]
You can export both the the SessionLog and the DebugLog.  You set these options in the `Open-WinSCPSession` command: https://github.com/dotps1/WinSCP/wiki/New-WinSCPSession
