### ISSUE TITLE
New-WinSCPSessionOption Issue

### ISSUE THREAD

**Issue by maguss4o** [dotps1/WinSCP#141]
When running the script as a Scheduled task it is freezing on $sessionOption = New-WinSCPSessionOption ... line. If the script is run manually from the Powershell console there are no issues. 

The following parameters are set on the task: -executionpolicy unresctricted, -noninteractive and -nologo

**Comment by maguss4o** [comment]
> New-WinSCPSessionOption

It is New-WinSCPSessionOption. I have log file on the executed steps. It is ending just before calling New-WinSCPSessionOption and i have manually to stop and start the task. When it is run manually via the console there are no issue and the full script runs.

**Comment by martinprikryl** [comment]
That's now that I have asked you. Please read my question again.

**Comment by maguss4o** [comment]
> That's now that I have asked you. Please read my question again.

It was New-WinSCPSessionOption specifically until today when i found in log that the argument cannot be associated with Credentials parameter because it is null when it is run as Scheduled task. It is very likely an issue with the PSCredential object. I will check that. 

What do you mean with "What about New-WinSCPSession" ? I'm providing the options as SessionOption object.  If SessionOption is null it can not proceed creating a session. 

Anyway i will check how i call the credentials now.

**Comment by martinprikryl** [comment]
Ok, so try another cmdlet that does not need any other WinSCP object as an imput. Like `New-WinSCPTransferOption`.

**Comment by maguss4o** [comment]
> Ok, so try another cmdlet that does not need any other WinSCP object as an input. Like `New-WinSCPTransferOption`.

Sorry for the late reply. I found the issue. The Credential object is null and so the new-winscpsessionoption hangs or it is returning an error after a lot of time. 

The reason for the empty credential object was the configuration of the task and the impossibility of converto-securestring to read the encrypted password.

**Comment by tomohulk** [comment]
Check out Dave Wyatts ProtectedData module, that is how I handle securing passwords at rest for tasks such as this.
