### ISSUE TITLE
Typo in function Remove-WinSCPItem

### ISSUE THREAD

**Issue by habsgoalie** [dotps1/WinSCP#18]
Hi,

I've run into a small bug: When calling function Remove-WinSCPItem from a script I get the following error - 

```
Property 'ValueFromPipelingByPropertyName' cannot be found for type 'System.Management.Automation.ParameterAttribute'.
At C:\Program Files\WindowsPowerShell\Modules\WinSCP\5.7.4.3\Functions\Remove-WinSCPItem.ps1:49 char:9
+         [Parameter(Mandatory = $true,
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFoundForType
```

The parameter attribute appears to be a typo in the function - `ValueFromPipelingByPropertyName` rather than `ValueFromPipeline`. I could fix this myself but I am new to Github and don't quite know how to contribute my own bugfix or if it is appropriate to do so. Thanks!

**Comment by dotps1** [comment]
Great catch, i updated the code.  It was a typo, but the attribute was what i was intending ```ValueFromPipelineByPropertyName = $true```
https://technet.microsoft.com/en-us/library/hh847824.aspx?f=255&MSPPError=-2147217396

thanks again.
