### ISSUE TITLE
Issue with Receive-WinSCPItem

### ISSUE THREAD

**Issue by Edzilla2000** [dotps1/WinSCP#19]
With the recent updates, you have changed the way Receive-Winscpitem works:
Before, it was possible to set "destination" to a filename different from path, and the file would be renamed locally to that filename.

For example, if I have a Path of "./filename.txt" and a Destination of "c:\tmp\temporary.txt", the file would be renamed locally to "temporary.txt".

Now there is this check:
if ((Get-Item -Path $Destination).Attributes -eq 'Directory' -and -not $Destination.EndsWith('\'))
            {
                $Destination += '\'
            }

It I specify a local filename as $destination tries to do a "get-item" of a not-yet existing path, and throws an error.

Could it be possible to revert to the previous behavior?

**Comment by dotps1** [comment]
Added ```-ErrorAction SilentlyContinue``` to the Get-Item Check, so if it can get the dir, and their is no trailing '\' then it will add it so the file will be transferred in that dir, rather then downloading the file to the intended dir and name that file said dir.
