### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by CermakPOI** [dotps1/WinSCP#2]
The Help 
<# 
SYNOPSIS ...

should bi directly after the 
function Name {
not in front of it 
;-)

**Comment by dotps1** [comment]
I would not consider this an 'Issue', if you would like to have the help inside the Function code block, feel free to fork or clone the source code and do so.  However, per the Microsoft article about_Comment_Based_Help, found here: https://technet.microsoft.com/en-us/library/hh847834.aspx you can have your help blocks either before the function, inside the function block before the Param block, or at the end, but still inside the function block.
Thank you for your feedback, have a good day
