### ISSUE TITLE
Issue with file checksum

### ISSUE THREAD

**Issue by Edzilla2000** [dotps1/WinSCP#20]
In Get-WinSCPItemChecksum

"ValueFromPipelineByProperyName" should be "ValueFromPipelineByPropertyName"

[Parameter(Mandatory = $true,
                   ValueFromPipelineByPropertyName = $true)]
        [ValidateScript({ -not ([String]::IsNullOrWhiteSpace($_)) })]
        [String[]]
        $Path

**Comment by dotps1** [comment]
Corrected Type, Download 5.7.4.6.
