### ISSUE TITLE
Confirmation in Remove-WinSCPItem

### ISSUE THREAD

**Issue by Edzilla2000** [dotps1/WinSCP#21]
Currently Remove-WinSCPItem asks for manual confirmation on all deletes.
This is not really useful in a scripting context :)
Is it possible to add a -force to change this behavior to delete without confirmation?

**Comment by dotps1** [comment]
I thought i had already added this functionality.  Good Catch.  I have added a -Force Switch to the cmdlet, could you please see if it is working out for you now.  I'm in the middle of my WIn10 upgrade so i don't have an FTP server set up to test.  Thanks.

**Comment by dotps1** [comment]
actually, scratch that -Force switch, because of default cmdletbindings you can user the -Confirm Switch natively.
```PowerShell
Remove-WinSCPItem -WinSCPSession $session -Path './REMOVEME.txt' -Confirm:$false
```
I have tested this and it works.

Thanks.
