### ISSUE TITLE
new-winscpitem does not create folder and errors out

### ISSUE THREAD

**Issue by Edzilla2000** [dotps1/WinSCP#22]
I try to create a directory if it does not exist:
if (-not (Test-WinSCPPath -WinSCPSession $session -Path $HistoryPath))
	{
		New-WinSCPItem -WinSCPSession $session -Path $name -ItemType Directory
	}

The folder does not get created and I get this error:

Get-WinSCPItem : Cannot find path: ./VanBreda/ because it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\WinSCP\Functions\New-WinSCPItem.ps1:90 char:17
+                 Get-WinSCPItem -WinSCPSession $WinSCPSession -Path $p
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-WinSCPItem

**Comment by dotps1** [comment]
can you give me your values of $HistoryPath and $name so I can emulate some tests?  thanks.

**Comment by dotps1** [comment]
I have updated this cmdlet because of another issue I found.  Can you please download the latest and give it another try?  I was not able to reproduce this bug.
This version is not published on the PowerShellGallery yet so you will have to download it from here.  I wanted to wait till you tested it before I did that.  thank you.

**Comment by Edzilla2000** [comment]
I will try to test it as soon as possible.
$HistoryPath was "/VanBreda" and $name was "VanBreda"

**Comment by dotps1** [comment]
stand by on testing, it is still failing, thanks.

**Comment by dotps1** [comment]
Ok, I think I fixed it.  I also added the -Name parameter to the cmdlet to match the native functionality of powershell, New-Item
```PowerShell
New-WinSCPSession -WinSCPSession <WinSCP.Session> [-Path <String[]>] [-Name <String>] [-ItemType <File | Directory>] [-Value <String>] [ -CommonParameters]
```
![image](https://cloud.githubusercontent.com/assets/1016996/9666785/338accfa-5246-11e5-91bb-8a8f5d616b05.png)

please test and confirm for me, I will get it updated on the PowerShellGallery as well.  thanks.

**Comment by dotps1** [comment]
Have you had a chance to test this in your environment yet?

**Comment by Edzilla2000** [comment]
Sorry no, won't be able to until Monday

Le sam. 5 sept. 2015 16:46, Thomas Malkewitz <notifications@github.com> a
écrit :

**Comment by Edzilla2000** [comment]
It looks like it's fixed, thanks!

**Comment by dotps1** [comment]
Awesome, thanks for letting me know.
