### ISSUE TITLE
Sync to full destination path

### ISSUE THREAD

**Issue by djsmith** [dotps1/WinSCP#25]
I'm trying to sync to a customer's server and by default it sets the sftp session's working directory to the account's home directory, but I need to sync the files to /D/Sites/wwwroot.

When I use "/D/Sites/wwwroot" as the destination parameter it appends a dot to the beginning of the path (via the Format-WinSCPPathString cmd) making it a relative path, and so the sync errors:
`Sync-WinSCPPath : Cannot find path: ./D/Sites/wwwroot because it does not exist.`

Is there anyway to use a full path as the destination, not a relative one?

Thanks
Dan

**Comment by dotps1** [comment]
By design, it will always use a relative path.  But you do bring up a good point.  I would say the fastest thing for you to do would be to remove the block from the Format-WinSCPPathString.ps1
```PowerShell
    if (-not ($Path.StartsWith('.'))) {
        $Path = ".$Path"
    }
```
Without developing a better solution, that is best i have for now.

**Comment by dotps1** [comment]
actually, no don't do that, because the next statement will make it go `//D/Sites/wwwroot`

replace the `Format-WinSCPPathString` with this:
```PowerShell
Function Format-WinSCPPathString {
    [OutputType([String])]

    Param (
        [Parameter(
            Mandatory = $true
        )]
        [String]
        $Path
    )

    if ($Path.Contains('\')) {
        $Path = $Path.Replace('\','/')
    }

    if (-not ($Path.StartsWith('/'))) {
        $Path = "/$Path"
    }


    if (-not ($Path -match '\.[^.]+$') -and -not ($Path.EndsWith('/'))) {
        $Path = "$Path/"
    }

    return $Path
}
```

hope that helps.

**Comment by dotps1** [comment]
Actually, i think i got this all cleaned up and fixed, basically if you have a '.' at the beginning of the path, it will leave it, if you don't it will just make user the path starts with '/'.  If you want to download the latest and try it, please feel free.  If you do, please let me know the outcome.  Thanks.

**Comment by dotps1** [comment]
Ok, got this tested today, the -Path param now accepts full paths.

**Comment by djsmith** [comment]
Thanks for fixing the problem, works like a charm!

**Comment by dotps1** [comment]
hey, no problem, thanks for the feedback.
