### ISSUE TITLE
ValueFromPipelineByPropertyName = true

### ISSUE THREAD

**Issue by revelation1** [dotps1/WinSCP#26]
Hi,

Could you please add this to more named parameters?  The obvious examples are  hostname/port/protocol of New-WinSCPSession.  I see you already have it on $SshHostKeyFingerprint.  

I tend to pull these parameters from a database.  Being able to Pipe these parameters by splatting them using a hash table or custom object would be sweet.

Great job on this btw.  Been using in production for a while.

**Comment by revelation1** [comment]
Similarly, forcing user inputted credentials means this cannot be used in a background process which is somewhat crippling.  Allowing people the option to pass a credential would be awesome. Something like this...

        [Parameter(
			Mandatory = $true,
            ValueFromPipelineByPropertyName = $true
        )]
        [PSCredential]
		$Credential,
        [ValidateScript({ 
            if (!($Credential)) { 
                $Credential = Get-Credential
            } 
        })]

**Comment by dotps1** [comment]
I agree with the ValueFromPipelineByPropertyName, as far as your other comment, that is essentially how the code is now.  and you can Serialize your credential objects to disk with Export-Clixml and then import them back into your scripts with Import-Clixml.  this will also use DPAPI and encrypt your credentials.

```PowerShell
    Param (
        [Parameter(
            ValueFromPipeline = $true
        )]
        [PSCredential]
        $Credential = (Get-Credential),
```

that is essentially the same as the example your provided, it will only prompt you if your not passing credential object to that parameter.  and with `Mandatory = $true` attribute its going to prompt you everytime, no matter what.

thanks for the feedback.

**Comment by revelation1** [comment]
I incorrectly used the term splatting.  I usually pass a credential object on the pipeline and New-WinSCPSession is ignoring it.

This can be shown by the following code which requests credentials twice, essentially ignoring my passed parameter and the property ValueFromPipeline = $true.  

Get-Credential | New-WinSCPSession -HostName test.com

I may be missing something obvious but this looks like a PS bug.  Anyway, the code I provided earlier acts in the expected manner and only requests a credential if one is not piped.

**Comment by dotps1** [comment]
ok ok, I see what you are saying, I didn't know you where getting asked twice.  I will fix this in an upcoming release, I am making some other tweaks and changes as well.

you don't need the ValidateScript() parameter attribute, this works:
```PowerShell
        [Parameter(
            ValueFromPipeline = $true,
            ValueFromPipelineByPropertyName = $true
        )]
        [PSCredential]
        $Credential = (Get-Credential)
```
Thanks for clarifying the issue.

**Comment by dotps1** [comment]
ok, thanks for clarifying that you where getting the issue twice.  However, you do not need the Validate Script parameter attribute.  This works:

```PowerShell
[Parameter(
    ValueFromPipeline = $true,
    ValueFromPipelineByPropertyName = $true
)]
[PSCredential]
$Credential
```

I will get this added to an upcoming release, I'm working on fixing some other stuff, and getting some Pesters integrated into the solution.

Thanks again!

**Comment by dotps1** [comment]
This is corrected no in my latest check in, however, the build is not stable yet.  but I am going to close this now.

thanks again.
