### ISSUE TITLE
New-WinSCPTransferOption -PreserveTimeStamp $false 

### ISSUE THREAD

**Issue by revelation1** [dotps1/WinSCP#28]
The object returned does not have PreserveTimeStamp set to False.

Instead, it has FileMask set to False which breaks a subsequent Receive/Send.

Bizarre I know.  :)

**Comment by dotps1** [comment]
As that param is of type switch and not type bool, it needs to be declared like this:

```PowerShell
-PreserveTimeStamp:$false
```
hope that helps.

**Comment by dotps1** [comment]
The more i thought about this, i think it should be of type `[Bool]`.  I have updated the code here on GitHub, but i am not going to publish a new version on the PowerShellGallery for this fix, i will wait until my next release.  so this should work now:
```PowerShell
-PreserveTimestamp $false
```
thanks.

**Comment by revelation1** [comment]
Great!  thanks again
