### ISSUE TITLE
Non-terminating errors not powershell standard

### ISSUE THREAD

**Issue by revelation1** [dotps1/WinSCP#29]
Hi again,

I am finished with my project but I just wanted to let you know of one more bug/enhancement request.

I use $ErrorActionPreference and the -ErrorAction property fairly regularly but your try/catch around WINSCP methods is not working properly.  This method of error trapping will not throw if the file transfer is unsuccessful.

```
try{
    $WinSCPSession.GetFiles('/fakepath/','C:\TEMP',$false, (New-Object -TypeName WinSCP.TransferOptions)) 
}
catch {
    Write-Error 'This should error but does not.'
}
```

What has been necessary for me whenever sending or receiving files using your module is to add the following code.

```
$GetResults = Receive-WinSCPItem -WinSCPSession $WinSCPSession -Path '/fakepath/' -Destination 'C:\TEMP'
IF ($GetResults.IsSuccess -ne $true) {Write-Error $GetResults.Failures}
```

It would be great if you would add something like this to the relevant methods so that native powershell error handling started working.

**Comment by dotps1** [comment]
sorry it has taken me so long to get to this, been super busy with some other projects.  I really do like the idea and will give it some thought.
