### ISSUE TITLE
Open Session Handling

### ISSUE THREAD

**Issue by jbruett** [dotps1/WinSCP#3]
Another session handling option could be to accept a session object, opened or closed, and manage the session internally.  if the session was opened when it was passed you should leave it opened, otherwise it should be closed.  The WinSCP wiki PowerShell examples only take an object, and explicitly open and close the session around the action taken.

**Comment by dotps1** [comment]
Basically, the way i designed this was if you pipe the session object into any cmdlet, it will auto close.  that way it can all be done in one or two lines of code.  If you would like to leave the session open you can save it to a variable, that way the same session can be used on multipule commands.

```PowerShell
$opts = @{
     HostName = 'ftp.org'
     UserName = 'UserName'
     Password = 'P@$$W0rD'
}

# Leave session open.
$session = Open-WinSCPSession -SessionOptions (New-WinSCPSessionOptions @opts)
Get-WinSCPItem -Session $session -RemotePath ./folder/file.txt -LocalPath .\folder\file.txt
Send-WinSCPItem -Session $session -LocalPath .\folder\file.zip -RemotePath ./folder/file.zip
Close-WinSCPSession -Session $session

# Auto close session after receiving item.
Open-WinSCPSession -SessionOptions (New-WinSCPSessionOptions @opts) | Get-WinSCPItem -RemotePath ./folder/file.txt -LocalPath .\folder\file.txt
```

I do understand what you are saying, but i think for now i am going to leave it the way it is.  Feel free to fork the repo and edit how you see fit.

Thanks for the feed back.
