### ISSUE TITLE
Cannot install 5.7.6 on 2012 R2 with WMF 5.0 Preview

### ISSUE THREAD

**Issue by jdomann** [dotps1/WinSCP#31]
I was trying to install 5.7.6 on my home server and found that no matter what I tried, it would not install.
5.7.4 installed however, but upgrades or clean installs did not work.
Oddly, on my Windows 10 system, it installed with no issues.
Here's a copy of the powershell log (cleaned up) from my server.
[winscplog.txt](https://github.com/dotps1/WinSCP/files/46790/winscplog.txt)
Here's a screenshot of the error in powershell:
![winscpscreenie](https://cloud.githubusercontent.com/assets/10852161/11460881/a278176c-96bb-11e5-9795-985751bd2a34.PNG)

Please let me know if you need anything from me, I'll be happy to provide it :)

**Comment by dotps1** [comment]
this is very strange, the only thing i can think of is because its WMF 5.0 Preview.  Can you install any other modules from the PowerShellGallery?

**Comment by jdomann** [comment]
Yeah, I thought about that as well, so I installed AzureRM.profile, the top package in the repository, and it worked fine.  Even installing the 5.7.4 rev worked fine oddly enough.

**Comment by dotps1** [comment]
one other thing i noticed is the output of `get-packageprovider|select name,version` from your log, and on my Win10 Box do not produce the same results:

Yours:
```
PS C:\Windows\system32> get-packageprovider|select name,version

Name       Version
----       -------
Programs   10.0.10514.6
Chocolatey 2.8.5.101
msu        10.0.10514.6
NuGet      2.8.5.101
msi        10.0.10514.6
PSModule   1.0.0.0
```

Mine:
```
PS C:\> get-packageprovider|select name,version

Name          Version
----          -------
Chocolatey    2.8.5.101
msi           3.0.0.0
msu           3.0.0.0
NuGet         2.8.5.101
PowerShellGet 1.0.0.1
Programs      3.0.0.0
```

Mine does not have the `PSModule 1.0.0.0` not sure what that is.  but it is a difference.

**Comment by dotps1** [comment]
the only thing i can think of, between version 5.7.6 and 5.7.4, is i updated the manifest, which contains a lot of metadata used by the PowerShellGallery
```
# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @(
            'Ftp'
            'Sftp'
            'WinSCP'
        )

        # A URL to the license for this module.
        LicenseUri = 'https://raw.githubusercontent.com/dotps1/WinSCP/master/LICENSE.md'

        # A URL to the main website for this project.
        ProjectUri = 'http://dotps1.github.io/WinSCP'

        # A URL to an icon representing this module.
        IconUri = 'http://winscp.net/eng/images/og_logo_240x240.jpg'

        # ReleaseNotes of this module
        ReleaseNotes = 'Attribute issue with -Credential Param in New-WinSCPSession:  https://github.com/dotps1/WinSCP/issues/26 < /br>
        Convert New-WinSCPTransferOption -PreserveTimeStamp from type Switch to Bool:  https://github.com/dotps1/WinSCP/issues/28 < /br>
        Fix -Path not taking String[] values:  https://github.com/dotps1/WinSCP/issues/30 < /br>
        Remove source file check on Send/Receive/Move-WinSCPItem allowing for wildcards to work:  https://github.com/dotps1/WinSCP/issues/27'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://raw.githubusercontent.com/dotps1/WinSCP/master/en-US/WinSCP-Help.xml'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = 'WinSCP'
```
So, your version of WMF may not be liking this.  open up the .psd1 from the other module you installed, and see if it contains these settings.

**Comment by jdomann** [comment]
When I installed the module to my Win10 box, I noticed that it had to install Nuget (and used a newer version) before pulling the module:
```
PS C:\WINDOWS\system32> Install-Module -Name WinSCP

NuGet provider is required to continue
PowerShellGet requires NuGet provider version '2.8.5.201' or newer to interact with NuGet-based repositories. The NuGet
 provider must be available in 'C:\Program Files\PackageManagement\ProviderAssemblies' or
'C:\Users\jdomann\AppData\Local\PackageManagement\ProviderAssemblies'. You can also install the NuGet provider by
running 'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force'. Do you want PowerShellGet to install
and import the NuGet provider now?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): y

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y

PS C:\WINDOWS\system32> Get-PackageProvider|select name, version

Name          Version
----          -------
Chocolatey    2.8.5.130
msi           3.0.0.0
msu           3.0.0.0
NuGet         2.8.5.201
PowerShellGet 1.0.0.1
Programs      3.0.0.0
```

**Comment by jdomann** [comment]
AzureRM.Profile.psd1 apparently does not have anything for PrivateData:

```
# Private data to pass to the module specified in ModuleToProcess  
PrivateData = ''  
```

I can try installing some more modules to test this theory out.

**Comment by dotps1** [comment]
i think it may either be that, or some thing with your providers on the server, your win10 box and mine, match up pretty close.  i don't have a non prod 2012 r2 box i can install WMF 5 on to test further.

**Comment by jdomann** [comment]
Yeah, I downloaded the module .zip from your website and unzipped it to the Program Files module path and importing it worked fine, so I have no idea why it isn't working.  I get a strong feeling it's probably related to how WMF 5.0 is implemented in Preview vs Windows 10, as I've noticed a number of differences between the two.

**Comment by dotps1** [comment]
right on, well let me know what you find, I'm going to close this just because i don't believe its truly related to the WinSCP module itself.  thanks.
