### ISSUE TITLE
Issue with Send-WinSCPItem

### ISSUE THREAD

**Issue by bilodeauj** [dotps1/WinSCP#32]
Hi I just tried you WinSCP for PowerShell and want to report an issue.
I've been trying to get file uploads working and used the following

$Session = New-WinSCPSession -Credential $FTPCredentials -HostName $FTPServer -Protocol Sftp -GiveUpSecurityAndAcceptAnySshHostKey

$TransferOptions = New-WinSCPTransferOption -PreserveTimestamp $True -TransferMode Binary

$Send = Send-WinSCPItem -WinSCPSession $Session -Path 'E:\Folder\file_name.txt' -Destination '/Home/CSV/file_name.txt' -TransferOptions $TransferOptions

$Send | FL

I get this as an output

Transfers : {E:\Folder\file_name.txt}
Failures  : {WinSCP.SessionRemoteException: Cannot create remote file '/Home/CSV/Home/CSV/file_name.txt/file_name.txt.filepart'. ---> 
            WinSCP.SessionRemoteException: General failure (server should provide error description).
            Error code: 4
            Error message from server: failed to open file
               --- End of inner exception stack trace ---}
IsSuccess : False

I editited the Send-WinSCPItem.ps1 and changed 
$WinSCPSession.PutFiles($item, (Format-WinSCPPathString -Path $($Destination)), $Remove.IsPresent, $TransferOptions)

To this

$WinSCPSession.PutFiles($item, $Destination, $Remove.IsPresent, $TransferOptions)

It looks the Format-WinSCPPathString function is messing up the string.

**Comment by dotps1** [comment]
I will look into this today.  thanks for reporting!

**Comment by dotps1** [comment]
ok, I have identified the bug, the fastest solution is to either, leave it the way you have it modified, or in your destination string, do not specify the file name.  `/Home/CSV`.  I will notify when I have true fix inplace.  thanks again for reporting.
