### ISSUE TITLE
Error "$LocalPath must be a directory."

### ISSUE THREAD

**Issue by crypticgeek** [dotps1/WinSCP#35]
So I'm getting an error when I attempt a Sync-WinSCPPath command.
```
PS> Sync-WinSCPPath -RemotePath '\home\user\folder\' -LocalPath 'C:\some\folder\here\ -Mode Remote 
Sync-WinSCPPath : C:\some\folder\here\ must be a directory.
At line:10 char:1
+ Sync-WinSCPPath -RemotePath '\home\user\folder\' -LocalPath 'C:\some\folder\here\' 
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Sync-WinSCPPath
```
At first I thought maybe I specified the folder wrong or I terminated with a slash and it needs it without, but that's not it. So I set a breakpoint on line 73 of Sync-WinSCPPath.ps1 which is the Write-Error command from this bit of code
```        
} else {
            $LocalPath = Get-Item -Path $LocalPath

            if (-not ($LocalPath.PSIsContainer)){
                Write-Error -Message "$LocalPath must be a directory."

                continue
            }
```
In the debugger

```
[DBG]: PS C:\>> $LocalPath.GetType();

IsPublic IsSerial Name                                     BaseType                                                                        
-------- -------- ----                                     --------                                                                        
True     True     String                                   System.Object    
```

Huh? How? In a normal powershell window:

```
PS> $p = 'C:\some\folder\here\'

PS> $p = Get-Item -Path $p

PS> $p.GetType()

IsPublic IsSerial Name                                     BaseType                                                                                                                    
-------- -------- ----                                     --------                                                                                                                    
True     True     DirectoryInfo                            System.IO.FileSystemInfo  
```
I don't understand how that variable could possibly have turned into a string. I mean you're reusing that variable with get-item, but I don't see an issue with that. It's almost as if that line of code with Get-Item isn't being ran but I know it is because I toggled a break point there and stepped into it as well and afterwards it's still a string! I'm stumped.

**Comment by dotps1** [comment]
Thanks for letting me know about this.  This is one function that I don't have Pesters written for yet.

I really have no explination for what is going on, other then that maybe because I a declare `$LocalPath` as a string in the parameter attributes that it cannot expliciatly cast as a FileInfo or DirectoryInfo???  But I'm not sure.  rather then messing around with the casting, I just decided to make a new variable `$localPathInfo`

```PowerShell
        try {
            $localPathInfo = Get-Item -Path $LocalPath -ErrorAction Stop

            if (-not ($localPathInfo.PSIsContainer)){
                Write-Error -Message "$($localPathInfo.FullName) must be a directory."

                continue
            }
        } catch {
            Write-Error -Message "Cannot find path: $LocalPath because it does not exist."

            continue
        }
```

thanks again, I will get this published to the PSGallery and you should be able to update your module version.

thanks.

**Comment by crypticgeek** [comment]
Thanks for the quick reply. Yeah I guess the parameter assignment may have something to do with it. Tested and it's working for me.
