### ISSUE TITLE
New-WinSCPTransferOption FileMask does not filter folders

### ISSUE THREAD

**Issue by smoofy** [dotps1/WinSCP#36]
Hello,

When using a FileMask files are being filtered but folders are selected:

`New-WinSCPTransferOption -FileMask '*.txt'`

Will catch `foo.txt` and `bar.txt` and `folder/`.
It will successfully ignore any other file.

**Comment by martinprikryl** [comment]
There's separate set of masks for files and folders.

To include only `*.txt` files, and exclude all folders, use `*.txt | */`.

See http://winscp.net/eng/docs/file_mask

**Comment by dotps1** [comment]
Thanks @martinprikryl.
