### ISSUE TITLE
DLL handling

### ISSUE THREAD

**Issue by jbruett** [dotps1/WinSCP#4]
Since this is a module why not add the dll handling as part of the module?  This would allow for strong typing of the variables in each cmdlet, instead of using parameter validation to ensure the proper values are being submitted.

**Comment by dotps1** [comment]
Im not sure what you mean here.  can you expand?

**Comment by jbruett** [comment]
I took a look at the module definition file and i think that the required assemblies handles the dll thoughts that I was having and it looks as if you are doing some strong typing in other functions (close-winscpsession), and it's just not consistent throughout the module.  

For example, in your New-WinSCPSessionOptions cmdlet, the first listed parameter is [string]$FTPMode.  You also include some specific validation to ensure the correct value is used.  Why not have that strongly typed to [WinSCP.FTPMode].  Not sure if this would actually eliminate the need for parameter validation as I originally stated but it is using the native object type which I imagine has some benefit.

**Comment by dotps1** [comment]
I changed the Object Types for the parameters, and it does handle the Validation natively, so thank for the suggestion.

I also updated the WinSCP Assembly to V5.7.

Thanks again for the feed back.
