### ISSUE TITLE
more examples

### ISSUE THREAD

**Issue by ewhitesides** [dotps1/WinSCP#45]
Request for more help examples for each command.

For example, for Sync-WinSCPPath, it's not very clear what the Mode options accomplish exactly (local, remote, both), unless you test them on your own.

**Comment by dotps1** [comment]
I don't have everything update, but its on my list.  Make sure you are going to GitHub Pages Repo for help.  http://dotps1.github.io/WinSCP/cmdlets.html

**Comment by dotps1** [comment]
Please see the new wiki:  https://dotps1.github.io/WinSCP/wiki
