### ISSUE TITLE
receive-winscpitem

### ISSUE THREAD

**Issue by ewhitesides** [dotps1/WinSCP#46]
receive-winscpitem needs to return an object even if the download attempt fails.  right now it doesn't, so i have to resort to creating a whole custom object based off the -errorvariable result.

**Comment by jbruett** [comment]
wouldn't you just check to see if the return value is not null?

**Comment by ewhitesides** [comment]
I need to interact with the values from the object in the same way if it
fails or succeeds.

Most of the Microsoft cmdlets like bits transfer operate this way.

**Comment by dotps1** [comment]
Can you give an example cmdlet?  in my head I'm thing about like `Get-Item`, that will throw an error if the item doesn't exist, so I'm not sure what your looking for exactly.

**Comment by ewhitesides** [comment]
I'll send some examples on Monday when I'm front a computer.

**Comment by ewhitesides** [comment]
It seems like some other cmdlets I've been using are with the async switch, and when the async switch is used an object is returned that can be interacted with.

perhaps then, my original request should be a request to set up winscp to allow async transfer jobs .

start-bitstransfer functions in a similar way, but below is an example with system.net.webclient of an async transfer job.  

            $client = New-Object System.Net.WebClient    
            $result = $client.DownloadFileTaskAsync($file.SourcePath,$file.DestinationPath)
            $result | Add-Member -Type NoteProperty -Name Destination -Value $file.DestinationPath
            $result | Add-Member -Type NoteProperty -Name Timestamp -Value $GivenTimestamp
            [array]$results += $result

            #Wait for Completion
    While ($results | Where-Object {$_.IsCompleted -eq $false})  {
        Sleep 5
    }

    #Remove the files that have a status of faulted
    $results | Where-Object {$_.IsFaulted -eq $True} | Select-Object -ExpandProperty Destination | 
    Remove-Item

**Comment by dotps1** [comment]
this module is basically a wrapper around the WinSCP.dll, and I don't see anything really in the docs saying that it supports async operations, and I'm not really sure a way to accomplish this other then opening a bunch of WinSCP.Sessions.

**Comment by ewhitesides** [comment]
For large scale downloads, I found a way to group files based on the same username,passowrd,fingerprint and server address, then open 1 session and copy all the files for that grouping.  If anyone finds it useful here's the code:

`#Group so multiple files can be transferred over one session (instead of one session per file transfer)
    $GroupedTargets = $GivenTargets | Group-Object -Property User,Password,SshFingerprint,Server

    ForEach ($GroupTarget in $GroupedTargets) {
        
        $user = $GroupTarget.Group.User[0]
        $password = $GroupTarget.Group.Password[0]
        $server = $GroupTarget.Group.Server[0]
        $sshfingerprint = $GroupTarget.Group.sshfingerprint[0]

        $securestringpasswd = ConvertTo-SecureString $password -AsPlainText -Force    
        $credentials = New-Object System.Management.Automation.PSCredential ($user, $securestringpasswd)
        $session = New-WinSCPSession -hostname $server -Credential $credentials -SshHostKeyFingerprint $sshfingerprint

        ForEach ($file in $GroupTarget.Group) {
        
            $DestinationFolder = Split-Path -Path $file.DestinationPath -Parent

            #If Destination Folder does not exist, create it.
            if (!(Test-Path $DestinationFolder)) {
                New-Item $DestinationFolder -ItemType Directory | Out-Null
            }

            #If File does not exist, Download
            Get-Item $file.DestinationPath -ErrorAction SilentlyContinue | Out-Null
                   
            if (!$?) {

                #Put results into custom object
                $result = New-Object -TypeName PSObject
                $result | Add-Member -Type NoteProperty -Name ID -Value $file.ID
                $result | Add-Member -Type NoteProperty -Name Timestamp -Value $GivenTimestamp
                $result | Add-Member -Type NoteProperty -Name SourcePath -Value $file.SourcePath
                $result | Add-Member -Type NoteProperty -Name DestinationPath -Value $file.DestinationPath
            
                #Session exists
                if ($session) {
                    
                    Test-WinSCPPath -WinSCPSession $session -Path $file.SourceFile

                    #File exists
                    if ($?) {                 
                        $outcome = Receive-WinSCPItem -WinSCPSession $session -Path $file.SourceFile -Destination $file.DestinationPath -ErrorVariable FileError
                        
                        #Download not successful
                        if (!$?) {
                            $result | Add-Member -Type NoteProperty -Name Status -Value 'Faulted'
                            $result | Add-Member -Type NoteProperty -Name Error -Value $FileError
                        }
                                
                        #Download successful
                        elseif ($outcome.IsSuccess -eq $True) {
                            $result | Add-Member -Type NoteProperty -Name Status -Value 'RanToCompletion'
                            $result | Add-Member -Type NoteProperty -Name Error -Value $null    
                        }          
                    }

                    #File does not exists
                    else {
                        $result | Add-Member -Type NoteProperty -Name Status -Value 'Faulted'    
                        $result | Add-Member -Type NoteProperty -Name Error -Value "File not found on server"
                    }
                }
                
                #Session does not exist
                else {
                    $result | Add-Member -Type NoteProperty -Name Status -Value 'Faulted'    
                    $result | Add-Member -Type NoteProperty -Name Error -Value "Connection error to SFTP server"     
                }
            [array]$results += $result
            }        
        }        
    }           
    Write-Output $results`

**Comment by ewhitesides** [comment]
some other issues i'm noticing:

test-winscppath -winscpsession $session -Path 'somefilethatdoNOTexist'
returns False

however, "$?" returns true

also, back to my original point:
$outcome = Receive-WinSCPItem -WinSCPSession $session -Path $file.SourceFile -Destination $file.DestinationPath

$outcome.IsSuccess should return $True if file downloads successfully, and $False when it fails.

**Comment by ewhitesides** [comment]
instead of async switch, i found a way to make the downloads over sftp very fast.

in an array of 20000 text files, it only took minutes to download.  By using Group-Object -Property User,Password,SshFingerprint,ServerIP , I grouped items that had the same server connection, thereby minimizing how many connections.

**Comment by dotps1** [comment]
ill take a look at the Receive-WinSCPItem thing when I get a minute.

as for the $? that is if the last Command complete, not what the outcome was, so the its like saying "Did Test-WinSCPPath Complete?"  even though the path you tested was non existent, hence the false, the cmd did complete.

**Comment by ewhitesides** [comment]
i guess i just have to test each cmdlet to get to know the subtle differences
something like 'get-childitem nonexistentfile.txt returns False for $?
but test-path nonexistentfile.txt returns false, but $? returns true

**Comment by dotps1** [comment]
that's because `Get-ChildItem -Path .\FakePath` will error, so $? will be false, because the command didn't complete opposed to `Test-Path -Path .\FakePath` will return $false because its a fake path, but $? will be true because the command completes.

**Comment by dotps1** [comment]
http://stackoverflow.com/questions/10634115/what-is-in-powershell
