### ISSUE TITLE
Session variable disposed after latest commits?

### ISSUE THREAD

**Issue by miltonthecat** [dotps1/WinSCP#5]
Hi, I am getting an "object is disposed" error for my session variable using the latest build. I am following this example from the documentation:

```
PS C:\> $session = New-WinSCPSessionOptions -Hostname myftphost.org -Username ftpuser -password "FtpUserPword" -SshHostKeyFingerprint "ssh-rsa 1024 xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx" | Open-WinSCPSession
PS C:\> Get-WinSCPDirectoryContents -WinSCPSession $session -Path "rDir/" -ShowDetails
```

I reverted to the 25-Jan-2015 build and the error disappears. Can you duplicate this issue?

**Comment by dotps1** [comment]
Should be all set now, thanks for the FYI.  I was playing with a TryCatchFinally, and forgot to remove the Finally block in the Open-WinSCPSession Cmdlet, so it was auto-disposing the session.

Thanks again.
