### ISSUE TITLE
Typo (?) - GiveUpSecureityAndAcceptAnyTlsHostCertificate

### ISSUE THREAD

**Issue by iokevins** [dotps1/WinSCP#51]
Noticed this long-standing naming discrepancy between WinSCP SessionOptions variable name and WinSCPWrapper parameter for New-WinSCPSession:

- WinSCP: GiveUpSecurityAndAcceptAnyTlsHostCertificate
- WinSCPWrapper: GiveUp**Secureity**AndAcceptAnyTlsHostCertificate

This seems to represent a bug:

- The New-WinSCPSession loop which assigns WinSCP.SessionOptions values seems to fail to identify GiveUp**Secureity**AndAcceptAnyTlsHostCertificate as a valid member of that object.
- As a consequence, upon attempting to open the session, I received this error, "New-WinSCPSession : Exception calling "Open" with "1" argument(s): "Connection failed. Peer certificate rejected Disconnected from server Connection failed.""

When I correct the parameter name, it seems New-WinSCPSession correctly identifies the WinSCP.SessionOptions member, from the bound parameter, and my connection succeeds.

Thank you,

Kevin

Links:
[https://winscp.net/eng/docs/library_sessionoptions](https://winscp.net/eng/docs/library_sessionoptions)
[https://github.com/dotps1/WinSCP/blame/master/WinSCP/Public/New-WinSCPSession.ps1#L34](https://github.com/dotps1/WinSCP/blame/master/WinSCP/Public/New-WinSCPSession.ps1#L34)

**Comment by dotps1** [comment]
wow, great find, its been like this for probably a year.  I will get this updated here in a moment, and get it out to the PSGallery.  Thanks!

**Comment by dotps1** [comment]
Great find, thanks again.  The reason this was failing is because of the logic, the named parameters match the property names of the `WinSCP.SessionOptions` object, so, it just loops through the parameter names and adds them when constructing the object, this allows for less code.  And if the parameter names are spelled wrong, well, the object constructor is going to be mad.  thanks again!  new version is published!

**Comment by iokevins** [comment]
It looks like the help files got updated in source code, but not this one (?):
[WinSCP/WinSCP/Public/New-WinSCPSession.ps1 ](https://github.com/dotps1/WinSCP/blob/master/WinSCP/Public/New-WinSCPSession.ps1)

**Comment by dotps1** [comment]
not sure what you mean.  this module uses external help, its an XML located in WinSCP\en-US\.  I updated the xml.  the link you have is to the source file, there is no help there

**Comment by dotps1** [comment]
OMG!  its building now, I only saved the help file changes not the actual source code file, I'm sorry.

**Comment by iokevins** [comment]
No need to apologize : )

I'm grateful for this software and for the speedy support!
