### ISSUE TITLE
Refactoring sessionValueFromPipeLine

### ISSUE THREAD

**Issue by iokevins** [dotps1/WinSCP#52]
_Very low priority; please feel free to disregard_

Time/motivation permitting, would you please consider refactoring variable "sessionValueFromPipeLine"? Namely, the following expression seems to return "True" not for pipeline values, but for other situations:
`$sessionValueFromPipeLine = $PSBoundParameters.ContainsKey('WinSCPSession')`

This seems counterintuitive to me, as this expression seems to assign variable sessionValueFromPipeLine the value False, when WinSCPSession is provided on the pipeline. This gets handled in the End block, as "if (-not ($sessionValueFromPipeLine)) {...", per auto-disposal when input provided on the pipeline. 

In summary, it seems to work, but the variable seems worded in a confusing way (to me). Maybe refactor it to something like "$sessionValueAutoRemove" = (-not $PSBoundParameters.ContainsKey('WinSCPSession'))"; (?) 

What do you think (?)

The following example lists a few situations which return true:

```
$Global:PSDefaultParameterValues.Remove("Test:Name")

Function Test {
  [CmdletBinding()]
  param(
  [Parameter(Mandatory = $True, ValueFromPipelineByPropertyName, ValueFromPipeline)]
  [string] $Name
  )
  begin { 
    $boundSessionValue = $PSBoundParameters.ContainsKey('Name')

  }
  process
  {
    "boundNameValue = $($boundSessionValue); " + "Name = " + $Name
  }
  end { 
  }

} # End Test

$NewLine = "`r`n"

# boundNameValue = True; Name = Fred
"Test -Name ""Fred""--explicitly bound parameter"
Test -Name "Fred"

# boundNameValue = True; Name = Fred
$NewLine + `
"Test ""Fred""--implicitly bound parameter"
Test "Fred"

# boundNameValue = False; Name = Fred
$NewLine + `
"""Fred"" | Test--implicitly bound pipeline parameter"
"Fred" | Test

$NewLine + `
"Setting `$Global:PSDefaultParameterValues"
$Global:PSDefaultParameterValues.Add("Test:Name", "Bob")

# boundNameValue = True; Name = Fred
$NewLine + `
"Test -Name ""Fred""--explicitly bound parameter"
Test -Name "Fred"

# boundNameValue = True; Name = Fred
$NewLine + `
"Test ""Fred""--implicitly bound parameter"
Test "Fred"

# boundNameValue = True; Name = Bob
$NewLine + `
"Test--no passed parameter, uses Global:PSDefaultParameterValues"
Test

# Error: overriding default with pipeline not allowed
#"""Fred"" | Test--override default with pipeline parameter"
#"Fred" | Test
```

Source files (search query follows):

1. WinSCP/Public/Invoke-WinSCPCommand.ps1
2. WinSCP/Public/Test-WinSCPPath.ps1
3. WinSCP/Public/Get-WinSCPItem.ps1
4. WinSCP/Public/Get-WinSCPItemChecksum.ps1
5. WinSCP/Public/Remove-WinSCPItem.ps1
6. WinSCP/Public/Move-WinSCPItem.ps1
7. WinSCP/Public/Receive-WinSCPItem.ps1
8. WinSCP/Public/Send-WinSCPItem.ps1
9. WinSCP/Public/Sync-WinSCPPath.ps1
10. WinSCP/Public/Rename-WinSCPItem.ps1
11. WinSCP/Public/Get-WinSCPChildItem.ps1
12. WinSCP/Public/New-WinSCPItem.ps1

Source file search query:
[https://github.com/dotps1/WinSCP/search?q=sessionValueFromPipeLine&type=Code&utf8=%E2%9C%93](https://github.com/dotps1/WinSCP/search?q=sessionValueFromPipeLine&type=Code&utf8=%E2%9C%93)

Again, very low priority. Please do what you prefer. If you're in the file to change something anyway, it might represent something to cleanup--it might help clarify this better for someone like me, in the future. : )

Thank you,

Kevin

**Comment by dotps1** [comment]
to be honest, I'm thinking i want to remove this functionallity.  And leave the disposing of the object to you.

with the use of the default params, when your done you would just call "remove-winscpsession" and it would go away.

**Comment by dotps1** [comment]
or maybe add a `-AutoDisposeSession` switch to all those cmdlets, then you can use that if you want to auto dispose the session after that command completes.

**Comment by iokevins** [comment]
Either way seems reasonable, to me. Thanks!

**Comment by dotps1** [comment]
I have decided to remove the functionality, but it will not be in production (IE the PowerShell Gallery) until WinSCP 5.10 is released.

Thanks.
