### ISSUE TITLE
DebugLogLevel Parameter, for New-WinSCPSession

### ISSUE THREAD

**Issue by iokevins** [dotps1/WinSCP#53]
If you are willing, would you please add parameter "DebugLogLevel", to Function New-WinSCPSession (?)

DebugLogPath exists, but not corresponding DebugLogLevel. 

For example:
```
        [Parameter()]
        [ValidateRange(0, 2)]
        [Int]
        $DebugLogLevel = 0,
```

Thank you,

Kevin

RESOURCES
[https://github.com/dotps1/WinSCP/blob/master/WinSCP/Public/New-WinSCPSession.ps1](https://github.com/dotps1/WinSCP/blob/master/WinSCP/Public/New-WinSCPSession.ps1)

[https://winscp.net/eng/docs/library_session#debugloglevel](https://winscp.net/eng/docs/library_session#debugloglevel)

**Comment by iokevins** [comment]
Thanks!

**Comment by dotps1** [comment]
This is in prod now, but it will not make it to the PowerShellGallery until the next build.

thanks.
