### ISSUE TITLE
Can't find "DebugLogLevel" property on session object

### ISSUE THREAD

**Issue by chrgraefe** [dotps1/WinSCP#59]
Hi,

in the documentation of WinSCP.NET .NET library is additional to the "DebugLogPath" property a "DebugLogLevel"with 0 as default and 2 as verbose log level.
Do you support this feature in your PowerShell wrapper?

https://winscp.net/eng/docs/library_session

kind regards

**Comment by dotps1** [comment]
this will be in the 5.10 build when that assembly is released.

https://github.com/dotps1/WinSCP/issues/53

thanks.
