### ISSUE TITLE
Feedback for Receive-WinSCPItem

### ISSUE THREAD

**Issue by megamorf** [dotps1/WinSCP#60]
Hey Thomas,

nice SCP wrapper :-)

While trying it out I ran into two small issues with 

```powershell
Receive-WinSCPItem -Path '/home/myuser/pulltest/*' -Destination C:\temp\ -Verbose -OutVariable Transfer
```

It returns this:
```
$Transfer[0]

   Destination: .C:/temp C:/temp C:/temp C:/temp

IsSuccess    Removal FileName                                                                                                                                                                             
---------    ------- --------                                                                                                                                                                             
True            True {a.txt, b.txt, c.txt, d.txt}     
```

1. The TransferOperationResult says Removal=$true even though I didn't specify the `-Remove` switch
2. The display format of the object lists the destination folder per copied item which is kind of redundant

That's it.

Keep up the good work :+1:

**Comment by dotps1** [comment]
interesting, did you use this repo, or did you install it from the PSGallery?  i only ask because this repo has a  lot of refactoring that are not in the gallery yet, and i think i fixed the Removal part already.  but i have not messed with the -OutVariable yet, so i will look at that when i get some free time.

thanks.

**Comment by megamorf** [comment]
I used the latest PSGallery version but I can retest the module from Github once you're done with the refactoring. 

:-)

**Comment by dotps1** [comment]
its pretty much done, just waiting for WinCSP to release the new version out of beta.  check out the readme, lots major changes, especially how the WinSCP.Session object is handled.  If you do test, let me know.  thanks!

**Comment by dotps1** [comment]
did you every test your issue with the latest?

**Comment by megamorf** [comment]
Not yet, but I have an active project at work that relies on the module so expect feedback this or next week :-)

**Comment by dotps1** [comment]
just wanted to check in your exp with this.  It will be going live soon.

thanks.

**Comment by dotps1** [comment]
closing, no response.
