### ISSUE TITLE
feature request in new version

### ISSUE THREAD

**Issue by ewhitesides** [dotps1/WinSCP#61]
In the upcoming version, could it be possible authenticate via public/private keypair only? 

In the current version, when I specify the -sshprivatekeypath, it still prompts for username/password

**Comment by dotps1** [comment]
is this not an issue?  I see you closed it.

**Comment by ewhitesides** [comment]
i solved the issue on my end after posting.  
i have to use a username along with a private key.  leaving the password field blank seems to work.
