### ISSUE TITLE
Bug in Format-WinSCPPathString causes failure in Test-WinSCPPath

### ISSUE THREAD

**Issue by samconn** [dotps1/WinSCP#63]
The 1-Jul-2017 commit to the Format-WinSCPPathString.ps1 file changed a "contains" test from ...

`if ($item.Contains('\')) {`

to ...

`if ($item -contains [System.IO.Path]::DirectorySeparatorChar) {`

The problem is that the intrinsic "`-contains`" is intended to evaluate elements of a collection, not a string. [StackOverflow post](https://stackoverflow.com/questions/18877580/powershell-and-the-contains-operator)

I discovered the issue after upgrading to WinSCP 5.11.0.0 when the following long-working code "broke":

`Test-WinSCPPath -Path "/upload" ...`

The internal `Format-WinSCPPathString` invocation returned "/\upload", which is an invalid path whereas a "\upload" path exists on the server I was connecting to.

**Comment by dotps1** [comment]
the char is now being tested with the `-match` operator.  Thanks for letting me know!  you can grab 5.11.0.1 from the gallery.

**Comment by samconn** [comment]
Thank you for the speedy fix and deployment to the gallery!
