### ISSUE TITLE
New-WinSCPSessionOption fails when privatekeypassphrase provided

### ISSUE THREAD

**Issue by sethmgray** [dotps1/WinSCP#64]
In Version 5.11.0.1 provide PrivateKeyPassPhrase parameter (as securestring) and you get error. 
New-WinSCPSessionOption : Exception calling "SecureStringToBSTR" with "1" argument(s): "Value cannot be null.
Parameter name: s"
At line:1 char:17

Bug clearly in New-WINSCPSessionOption.ps1 146 where incorrect variable name is checked (presumably copy/paste error from old New-WinSCPSession)

if ($privateKeyPassphraseUsed) {
		try {
			$PrivateKeyPassphrase = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
                [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR(
                    $SshPrivateKeySecurePassphrase
                )
            )
		} catch {
            $PSCmdlet.ThrowTerminatingError(
                $_
            )
		}
    }

**Comment by dotps1** [comment]
Thanks for letting me know!  fixed and pushed new version to the PSGallery, 5.11.0.2.

**Comment by sethmgray** [comment]
Typo still present in variable name ("PrivateKeySecurePassphrase") ... 

$privateKeyPassphraseUsed = $PSBoundParameters.ContainsKey(
        "PrivateKeyPassphrase"
    )
    if ($privateKeyPassphraseUsed) {
		try {
			$PrivateKeyPassphrase = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
                [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR(
                    $PrivateKeySecurePassphrase
                )
            )
		} catch {
            $PSCmdlet.ThrowTerminatingError(
                $_
            )
		}
    }

**Comment by dotps1** [comment]
dammit, lol ok, good now.  v5.11.0.3.

**Comment by sethmgray** [comment]
Still broken... PS won't let you set a securestring = actual string. You'll need a different variable to capture the value if you want a string - though I do question why you'd want to store it as a string at this point, especially when this variable is never used in this cmdlet again...  

New-WinSCPSessionOption : Cannot convert the "eirjer" value of type "System.String" to type
"System.Security.SecureString".
At line:1 char:7
+ $opts=New-WinSCPSessionOption -host  hostname -port 22 -Credent ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-WinSCPSessionOption], RuntimeException
    + FullyQualifiedErrorId : ConvertToFinalInvalidCastException,New-WinSCPSessionOption

**Comment by dotps1** [comment]
It is used again when the $PSBoundParameters are enumerated, its reliant on the ParameterNames to key to the WinSCP.SessionOptions object properties.  I only have this as a System.SecureString because the PSScriptAnalyzer  gets pissed when parameters that are "Passwords" are not SecureStrings, but because the assembly doesn't support it anyway, maybe ill just set it back to a String.

**Comment by dotps1** [comment]
The only other way to do it would be to add something silly like this

```powershell
    try {
		$privateKeyPassphraseAsString = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
            [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR(
                $PrivateKeyPassphrase
            )
        )
        
        $PSBoundParameters.Remove(
            "PrivateKeyPassphrase"
        )

        $PSBoundParameters.Add(
            "PrivateKeyPassprhase", $privateKeyPassphraseAsString
        )

        $PSBoundParameters
	} catch {
        $PSCmdlet.ThrowTerminatingError(
            $_
        )
}
```

**Comment by dotps1** [comment]
Posted on WinSCP to see if they'd consider using a SecureString over a String.  Will see what happens.

https://winscp.net/forum/viewtopic.php?p=79416#79416

**Comment by dotps1** [comment]
Martin is going to add this feature to the next Version of assembly:  https://winscp.net/tracker/show_bug.cgi?id=1557
As soon as that is done, this will work properly because there will be no translation for the object type.

**Comment by dotps1** [comment]
looks like this isn't coming till v 5.12.

**Comment by sethmgray** [comment]
Thanks for the update. Ill test when available

**Comment by dotps1** [comment]
i may just change it to be a String for the time being.

**Comment by dotps1** [comment]
looks like this has been fixed and is out, ill get it updated this week.  https://winscp.net/tracker/show_bug.cgi?id=1557  thanks.

**Comment by martinprikryl** [comment]
5.12 beta has not been released yet.

**Comment by dotps1** [comment]
lol, my fault didn't even see that, when you click the "complete list of changes" link I didn't realize it went to the latest version.  thanks for letting me know.

**Comment by dotps1** [comment]
this will be in the 5.13 PS release coming soon.
