### ISSUE TITLE
Question: has it been tested with PowerShell Core 6.0.0?

### ISSUE THREAD

**Issue by mi-hol** [dotps1/WinSCP#65]
Hi Thomas,
great work!
I'm looking for information about compatibility with the upcoming PS6 version.
The minimum version version is stated in readme.md as 'You need WMF 5 to use this feature'
In case you tested with a PS 6 beta already, would you mind to add this information or share any plans on this topic?
Thanks
Michael

PS: question is related to an issue I've encountered in my own  scripts using WinSCP. 
Details are logged at #https://github.com/PowerShell/PowerShell/issues/4295

**Comment by dotps1** [comment]
i have not tested with v6, TBH i havent even installed v6 yet.

**Comment by mi-hol** [comment]
@dotps1 I'd love to test but didn't see a script on github that would allow for that. Any hint greatly appreciated :)

**Comment by mi-hol** [comment]
just a status update.
I've started but lost access to the sftp server I used in the past. Setting up my own server to test didn't succeed yet. Maybe you'd have a hint?

**Comment by mi-hol** [comment]
@dotps1 would there perhaps exist a test environment I could use?

**Comment by martinprikryl** [comment]
WinSCP cannot work with PowerShell/NET .Core. It's a pure WinAPI application.

**Comment by dotps1** [comment]
thanks for the update @martinprikryl.  And I think that answers your question @mi-hol.  Martin is the developer of WinSCP.

**Comment by mi-hol** [comment]
@martinprikryl I understand the answer for non-Windows platforms but assuming its running on W10 it should actually work due to the backward compatibilty as explained in [https://blogs.msdn.microsoft.com/powershell/2017/07/14/powershell-6-0-roadmap-coreclr-backwards-compatibility-and-more/](url)
'Compatibility
Our goal with PowerShell Core is to remain as compatible with Windows PowerShell as technically possible. To that end, we’re leveraging a technology called .NET Standard 2.0 to provide binary compatibility with existing .NET assemblies. Many PowerShell modules depend on these assemblies (often times DLLs), so .NET Standard allows them to continue working with .NET Core. You can learn more about .NET Standard on the .NET Blog, YouTube, and via this excellent FAQ on GitHub.'

**Comment by martinprikryl** [comment]
Maybe you are correct. I'll look into it.

**Comment by martinprikryl** [comment]
Can you test it with this build? It includes .NET Standard 2.0 build of WinSCP .NET assembly (in `netstandard2.0` subfolder):
https://winscp.net/public/WinSCP-20180424rnetstandard2-Automation.zip

**Comment by dotps1** [comment]
Ill see if I can get something up with PS core later today or tomorrow.  Thanks @martinprikryl !

**Comment by martinprikryl** [comment]
Anything new?

**Comment by dotps1** [comment]
sorry @martinprikryl I have been swamped with work the past few months, ill try to set something up this weekend.

**Comment by wongwaijeremy** [comment]
I have just tried the .NET Standard 2.0 build in a .NET Core 2.0 Console App and it works.

**Comment by mi-hol** [comment]
https://github.com/PowerShell/PowerShell/pull/6958 should improve the situation even further when powershell core 6.1 will be release

**Comment by wongwaijeremy** [comment]
However I don't know how to make it works at ASP.NET CORE 2.0 web app though..
Here is the capture.
![image](https://user-images.githubusercontent.com/29251156/41952537-00fe44aa-7a03-11e8-9898-1d2ad1c3c0da.png)
I add the assembly at a class library project and put WinSCP.exe at the same directory.
Meanwhile I have a web host project.
Where should I put the WinSCP.exe or the assembly at?

**Comment by dotps1** [comment]
closing:  https://winscp.net/tracker/1640

**Comment by chuanjiao10** [comment]
i have seen  https://winscp.net/tracker/1640 , it say:fixed.
@dotps1  ,this module support ps 6 on linux version now ?
ps=v6.2.2 on centos7.6, winscp=v5.15.2.0


```
PS /root> import-module winscp
import-module : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At line:1 char:1
+ import-module winscp
+ ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
+ FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

```
