### ISSUE TITLE
Invoke-WinSCPCommand fails in version 

### ISSUE THREAD

**Issue by ewhitesides** [dotps1/WinSCP#67]
The following command fails in version 5.11.1.0 

Invoke-WinSCPCommand -Command "/usr/local/ldm/bin/pqmon 2>&1 | grep 'pqmon.c:466:main()'" -WinSCPSession $session

but succeeds in version 5.9.6.0

i noted the difference in the new version where you create the session differently, so it's not related to that.

**Comment by ewhitesides** [comment]
error output is 
'Invoke-WinSCPCommand : The term 'Write-OutputType' is not recognized'

**Comment by ewhitesides** [comment]
my command is very specific to what i'm running.  i tried a command as simple as 'ls -l' and got the same error if you try to reproduce it.

**Comment by dotps1** [comment]
Fixed in 5.11.1.1.

**Comment by ewhitesides** [comment]
thanks!
