### ISSUE TITLE
New-WinSCPTransferResumeSupport errors when using the -transferresumesupporstate switch

### ISSUE THREAD

**Issue by lostmojos** [dotps1/WinSCP#68]
New-WinSCPTransferResumeSupport -TransferResumeSupportState off
New-WinSCPTransferResumeSupport : The property 'TransferResumeSupportState' cannot be found on this object. Verify that the property exists and can 
be set.
At line:1 char:1
+ New-WinSCPTransferResumeSupport -TransferResumeSupportState off
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-WinSCPTransferResumeSupport], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException,New-WinSCPTransferResumeSupport

Any suggestions on resolving this?  I have not had much luck, but my powershell fu is lacking for this.  I am running 5.11.2 from the powershell gallery.

**Comment by dotps1** [comment]
Thanks for submitting this.  I had the wrong parameter name in that cmdlet.  should be `-State` not `-TransferResumeSupportState`, that is the type name.  grab v 5.11.2.1 from the gallery and you should be good to go.

**Comment by lostmojos** [comment]
Awesome, thank you.
