### ISSUE TITLE
Rename-WinSCPItem vs Move-WinSCPItem

### ISSUE THREAD

**Issue by TroyK04** [dotps1/WinSCP#69]
Hi Thomas,

I have some confusion regarding _Rename-WinSCPItem_ and _Move-WinSCPItem_.  The Wiki synopsis for _Move-WinSCPItem_ indicates that it allows one to move and/or rename a remote file, whereas, the Wiki examples (no synopsis yet defined) for _Rename-WinSCPItem_ seem to indicate that it can only rename a file in its existing location.  This makes sense to me, as it matches the behavior of the WinSCP interface when using **F2** to rename a file, or **Shift+F6** to Move and/or rename a file.  

Unfortunately, when I attempt to use _Move-WinSCPItem_ to move and rename a file, I receive an error indicating that the path does not exist (even though it does):

`Get-WinSCPChildItem -WinSCPSession $SourceSession -Path $FilePath -File | 
Where-Object {$_.Name -match $FileFilter} | 
ForEach-Object {Move-WinSCPItem -WinSCPSession $SourceSession -Path $_.FullName -Destination ($ArchivePath + "/" + $_.Name + "." + (Get-date -UFormat %Y%m%d%H%M%S) + ".COMPLETED")} `

> Cannot find path '/Main/Test/Process/Archive/2017/Test.txt.20171211123203.COMPLETED' because it does not exist.` 

Interestingly, I found that if I substitute _Rename-WinSCPItem_  for  _Move-WinSCPItem_, the command works, as desired, and file Test.txt is moved and renamed to  '/Main/Test/Process/Archive/2017/Test.txt.20171211123203.COMPLETED'

Not sure if this behavior is intentional, or perhaps caused by an error on my part, but wanted to make you aware.

Thanks for all your effort!

Troy

**Comment by dotps1** [comment]
I have converted the `Rename-WinSCPItem` to just use the logic from `Move-WinSCPItem`.  This is fixed in the version 5.13.
