### ISSUE TITLE
.NET 3.5 & PowerShell 3.0

### ISSUE THREAD

**Issue by tobimax** [dotps1/WinSCP#72]
Hi, 

Trying to get this to work on .NET 3.5 & PowerShell 3.0 but to no avail. I have changed a few settings but is there something fundamental that would prevent this from working?

Thanks

Toby

**Comment by dotps1** [comment]
.net 3.5 and PowerShell is not supported.

https://github.com/dotps1/WinSCP/blob/master/WinSCP/WinSCP.psd1#L32

You would have to fork this and redo a lot of code to make it work.  I would suggest upgrading your powershell version.

sorry.
