### ISSUE TITLE
remove parameter Sync-WinSCPPath

### ISSUE THREAD

**Issue by insayan** [dotps1/WinSCP#75]
Hi

I'm having some trouble using the -remove parameter with the Sync-WinSCPPath cmdlet. Currently using the following line, it syncs fine but the files in the source folder are not removed.

`Sync-WinSCPPath -WinSCPSession $session -Mode Local -remove -LocalPath "C:\Users\me\path\path\sync folder" -RemotePath "/Path/"`

The Wiki says -Remove needs to be set to true but either -remove $true and -remove true both don't work. I'm probably overlooking something but I'm not sure what.

Thank you.

**Comment by dotps1** [comment]
`-Remove` should work.  I just finished a major overhaul on this module, so its probably a bug.  Ill take a look tonight if I can and see if I can get it fixed for you.  Thanks for letting me know.

**Comment by dotps1** [comment]
so, the more I thought about this, I realized your using the wrong function for what your trying to accomplish.  The `Remove` switch removes the file from the destination, if its removed from the source.  its an "Obsolete" files.  See the WinSCP wiki here:  https://winscp.net/eng/docs/library_session_synchronizedirectories

if you want to receive the items once and remove them from the source, use `Receive-WinSCPItem -Remove`.

Thanks.
