### ISSUE TITLE
Navigate to path in single quotes

### ISSUE THREAD

**Issue by martinprikryl** [dotps1/WinSCP#77]
On behalf of @cpaulk87
https://winscp.net/forum/viewtopic.php?t=26243

> A bit of background on my situation:
> I am trying to write a script via PowerShell to check daily for new files at multiple addresses and pull any new files.  I initially did this manually; but due to many complications involving the hosts we are downloading from (frequent disconnections, file-transfer issues), this has become a very time-consuming task that I think should be automated and, after much research, thought that WinSCP via PowerShell may do well at solving this issue.
> 
> Here's the issue:
> The customer we are pulling these files from is using single quotes in the paths of some of their servers.  While I can see their other folders, I'm unable to get into the folders with single quotes.  When I try using Test-WinSCPPath, I always get False and when I try Get-WinSCPChildItem, I get a message saying there was an error while enumerating through a collection and that the directory listing could not be retrieved.  I'm using the exact path that I see in the WinSCP GUI and have tried various methods of providing the path, including using escape characters, but with no luck.
> Is there a way to script this to get into the folders?  I'd really appreciate your help! :)

**Comment by dotps1** [comment]
so, if im understanding this correctly,  the file path looks like this:
```
./home/dir/Monday's files/file.txt
```

**Comment by cpaulk87** [comment]
I should have provided an example.  The path is surrounded in single quotes.  Ex:
/'NH1KB.GF4D7.OLDGEN.FSBKP.'  I cannot navigate to this folder without the single quotes like I can with most other folders.  I'm beginning to wonder whether the single quotes are the entire issue, though.  These hosts have a few other directories that are like this, as well, and one of the hosts logs me straight into one of those folders when I connect.  From there, I can access other folders that aren't surrounded by single quotes, but I'm unable to navigate to folders that have the single quotes.  The odd thing is that when I FTP into the server via command line, I don't have an issue navigating to the folder - I can simply cd into the path, then I can see the files I need.

I think the issue might can be solved if I can change the remote working directory to the root directory, then navigate to the directory I need from the root, but I haven't found where I can do anything like change the remote working directory while using FTP or WINSCP via Powershell.  Is that possible, or might I need to find another method of scripting this?  Any suggestions are welcome - I'll learn whatever I have to in order to be able to automate this process.

Thank you for looking into this issue! :)

**Comment by martinprikryl** [comment]
So can you post a log file showing the problem?

**Comment by cpaulk87** [comment]
I don't have a log file, but I can show you the error messages I'm getting.

When I connect, I can use Get-WinSCPChildItem to get the root path and this is some of the output I get:
                                                                                                                     
```
Mode                  LastWriteTime     Length Name                                                                                                                                            
----                  -------------     ------ ----                                                                                                                                            
rwxrwxr-x     3/29/2018 11:29:00 AM            appl                                                                                                                                            
rwxr-xr-x      7/9/2016 12:00:00 AM            apps                                                                                                                                            
rwxr-xr-x       3/2/2018 1:01:00 PM            bin                                                                                                                                             
rwxr-xr-x      7/9/2016 12:00:00 AM            bto                                                                                                                                             
rwxrwxrwx      7/2/2016 12:00:00 AM            dev                                                                                                                                             
rwxrwxrwx      7/9/2016 12:00:00 AM            etc                                                                                                                                             
rwxrwxrwx      7/9/2016 12:00:00 AM            home                                                                                                                                            
rwxr-xr-x    12/30/2016 12:00:00 AM            lib                                                                                                                                             
rwxr-xr-x     4/25/2015 12:00:00 AM            opt                                                                                                                                             
rwxrwxr-x       4/2/2018 9:37:00 AM            R2744226                                                                                                                                        
rwxr-xr-x     7/18/2016 12:00:00 AM            samples                                                                                                                                         
rwxr-xr-x      7/2/2016 12:00:00 AM            sharedapps                                                                                                                                      
rwxrwxrwx      4/29/2018 2:49:00 AM            smpe                                                                                                                                            
rwxr-xr-x     4/25/2015 12:00:00 AM            SYSTEM                                                                                                                                          
rwxrwxrwx      7/2/2016 12:00:00 AM            tmp                                                                                                                                             
r-xr-xr-x      5/10/2018 9:00:00 AM            u                                                                                                                                               
rwxr-xr-x     4/25/2015 12:00:00 AM            usr                                                                                                                                             
rwxrwxrwx      7/9/2016 12:00:00 AM            var   

```

I can also successfully gci in the listed folders to get the files & folders in there, too.

If I try Get-WinSCPChildItem on the path I'm trying to get into (which doesn't show up when I gci), I get this error:

```
Get-WinSCPChildItem : An error occurred while enumerating through a collection: Error listing directory '/NH1KB.GF4D7.OLDGEN.FSBKP'.
Could not retrieve directory listing
CWD cmd failed : EDC5129I No such file or directory. (errno2=0x05190050).
At line:1 char:1
+ Get-WinSCPChildItem -WinSCPSession $session -Path 'NH1KB.GF4D7.OLDGEN ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (WinSCP.Session+...moteFiles>d__85:<DoEnumerateRemoteFiles>d__85) [Get-WinSCPChildItem], RuntimeException
    + FullyQualifiedErrorId : BadEnumeration,Get-WinSCPChildItem
```

I try all sorts of variations on the path, such as removing the single quotes, surrounding the single quotes with double quotes, using two sets of three single quotes, adding slashes into the path, using ` as an escape character for the single quotes...I can't find anything that works.  I should also note that even though I can access this folder through the WinSCP GUI, I get this same error in the GUI if I don't navigate to this folder from the root directory or a folder that is listed in the root directory (I initially log into a folder that also is surrounded by single quotes, but cannot access the folder in question from there - I have to back out into the root folder before I can access the folder I need).

**Comment by dotps1** [comment]
I can't actually get this to happen

![image](https://user-images.githubusercontent.com/1016996/39946027-98a7c03a-553a-11e8-8c7d-3c26d55e7c2d.png)

and i gotta say, having quotes in file/folder names, just seems bad, i would think it would lead to all sorts of wonky issues.

**Comment by dotps1** [comment]
I even put in in a nested folder, and used the `-Recusre` switch, and it still worked.  Maybe you don't have the latest version of the module, `5.13.1.2`?

**Comment by martinprikryl** [comment]
It probably not about the quotes. But rather about the remote system. It's IBM MVS or VMS or something like that. So in the end it can actually be WinSCP issue. But hard to tell without a log file.

**Comment by cpaulk87** [comment]
I don't know if log files are produced from the WinSCP GUI; but if they
are, I'll grab one and send it when I get back to work Monday.  If not,
I'll learn some WinSCP scripting and try to get a log produced that way.

You may be right that it's not really a single quotes issue.  I'll see what
I can discover about the remote system.

**Comment by dotps1** [comment]
You can use the `-DebugLogLevel`, `-DebugLogPath`, and `-SessionLogPath` parameters on `New-WinSCPSession` to output logfiles using the PowerShell Module: https://github.com/dotps1/WinSCP/wiki/New-WinSCPSession

**Comment by cpaulk87** [comment]
Here are some log files I put together.  The two prefixed with "GUI" are from the WinSCP GUI, where you can see in the first log that I tried various methods of getting into the folder by navigating to other folders.  Finally, I was able to get into the folder from one of the folders in the root directory (it's a hit or miss when it comes to which folders work - the folder that works this time for getting into the folder I need might not work the next time).  I then tried transferring a file so you could see what that looks like.

Then, I made a new connection where I set the remote directory to /usr (the folder that allowed me to access the folder I needed in the last connection) and you can see I was able to get straight into the folder I needed from the /usr folder.

Finally, made a Powershell log.  In the PS log, you can see that I tried connecting then navigating to the folder I needed, but with no success.  I later disconnected and tried to add /usr as my remote directory (like I had tried in the GUI), but I still couldn't access the folder I was trying to get to after doing that.

[GUI_CHI_PX0B20180514_094604.log](https://github.com/dotps1/WinSCP/files/2001228/GUI_CHI_PX0B20180514_094604.log)
[GUI_CHI_PX0B20180514_102000.log](https://github.com/dotps1/WinSCP/files/2001229/GUI_CHI_PX0B20180514_102000.log)
[PS_session_log.txt](https://github.com/dotps1/WinSCP/files/2001230/PS_session_log.txt)

**Comment by martinprikryl** [comment]
OK, that it' indeed not an issue of PowerShell Wrapper Module, but of WinSCP itself. WinSCP (and particularly .NET assembly) is not really compatible with IBM MVS servers.

**Comment by dotps1** [comment]
based on that, I am going to close this issue @cpaulk87 as its not an issue with the powershell module itself.

thanks.

**Comment by cpaulk87** [comment]
Okay.  Thank you for your help.
