### ISSUE TITLE
Using Receive-WinSCPItem with -LocalPath to non-existent file works but with error

### ISSUE THREAD

**Issue by rmbolger** [dotps1/WinSCP#82]
### Issue Description

When attempting to transfer a single file from a remote server to the local machine with a different file name than what it was known as on the server, you can use `Receive-WinSCPItem` with the `-LocalPath` parameter. If the local file specified does not already exist, the file transfer is successful, but an error is generated.

This seems to be caused by the code here that checks if the path is a container.
https://github.com/dotps1/WinSCP/blob/master/WinSCP/Public/Receive-WinSCPItem.ps1#L53

You can avoid the error by adding `-ErrorAction SilentlyContinue` to the `Get-Item` call.

### Example

```powershell
Receive-WinSCPItem -RemotePath /file.txt -LocalPath C:\new-file.txt
```

### Expected Output

No output is expected other than the transfer to succeed.

### Actual Output

```
Get-Item : Cannot find path 'C:\new-file.txt' because it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\winscp\5.13.4.0\Public\Receive-WinSCPItem.ps1:53 char:18
+             if ((Get-Item -Path $LocalPath).PSIsContainer -and -not $ ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\ProgramData\...c\suits-new.dat:String) [Get-Item], ItemNotFoundExcep
   tion
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
```

### WinSCP-PowerShell Version

```
ModuleType Version    Name                                ExportedCommands                                             
---------- -------    ----                                ----------------                                             
Script     5.13.4.0   winscp                              {ConvertTo-WinSCPEscapedString, Copy-WinSCPItem, Get-WinSC...
```

### Environment

Win10 Enterprise (1803)

```
Name             : ConsoleHost
Version          : 5.1.14409.1012
InstanceId       : 0347f6c2-fb8e-4010-a36d-315e9613cf97
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

**Comment by dotps1** [comment]
I really thought I fixed this, ill take a deeper look tomorrow.  thanks for letting me know.

**Comment by rmbolger** [comment]
Not super critical since the transfer still completes. Just an annoyance I thought I'd mention. I'm working around it in a script by just pre-creating an empty copy of the destination file first.

**Comment by dotps1** [comment]
I think im just going to `Test-Path` first, if it exists, then ill do the check for if its a container.
