### ISSUE TITLE
Issue in rename-WinSCPItem

### ISSUE THREAD

**Issue by Gianlu** [dotps1/WinSCP#83]
_Please fill in the following fields, replacing the values inside the brackets `{{ }}`._

### Issue Description

rename-WinSCPItem throws exception "Path not found". I think (I tried during debug) that the problem is Format-WinSCPPathString because it returns no value (the output is write-host).
Using `$destination` instead of `$destinationPath` in Move-WinSCPItem.ps1 solves the bug.

### Example

`rename-WinSCPItem -WinSCPSession $winSCPUploadSession -Path $tmpFileName -NewName  $($f.Name)
`

### Expected Output

No error

### Actual Output

Path not found

### WinSCP-PowerShell Version

```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.13.4.0   WinSCP                              {ConvertTo-WinSCPEscapedString, Copy-WinSCPItem, Get-WinSCPChildItem, Get-WinSCPHostKeyFingerprint...}  
```

### Environment

Windows 2012 R2, powershell 5.1.14409.1012

**Comment by dotps1** [comment]
Can you please give me examples of the paths in `-Path` and `-NewName`.  Thanks.

**Comment by theLoFix** [comment]
Hello @dotps1 do you have some update on this issue?I still gate te same error when try t use 'Rename-WinSCPItem' or even 'Move-WinSCPItem':


```
Rename-WinSCPItem -WinSCPSession $session -Path $entry -NewName $lockedFile

Move-WinSCPItem : Cannot bind argument to parameter 'Path' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\WinSCP\Public\Rename-WinSCPItem.ps1:50 char:9
+         Move-WinSCPItem -WinSCPSession $WinSCPSession -Path $Path -De ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Move-WinSCPItem], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Move-WinSCPItem
```

Generally variables looks like this:
```
$file
/path/folder1/folder2/folder3/filename.csv

$lockedFile
filename.csv.lock
```

**Comment by dotps1** [comment]
I think i have this all fixed, can your grab a copy from here and test it out?

```
PS C:\Users\dotps1\Documents\GitHub\WinSCP\Source> Rename-WinSCPItem -Path ./test.msi -NewName newName.msi -PassThru


   Directory: ./

Mode                  LastWriteTime     Length Name
----                  -------------     ------ ----
              12/12/2018 4:03:03 PM   55500800 newName.msi


PS C:\Users\dotps1\Documents\GitHub\WinSCP\Source> Move-WinSCPItem -Path ./newName.msi -Destination ./temp/newNewName.msi -PassThru


   Directory: ./temp

Mode                  LastWriteTime     Length Name
----                  -------------     ------ ----
              12/12/2018 4:03:03 PM   55500800 newNewName.msi
```

let me know if it all works, ill publish a new version to the powershell gallery.  Thanks.

**Comment by theLoFix** [comment]
Hello @dotps1 , I tested both _Rename-WinSCPItem_ and _Move-WinSCPItem_, for me now works like a charm. Thanks for quick turn around. :+1:

**Comment by dotps1** [comment]
https://www.powershellgallery.com/packages/WinSCP/5.13.6.1

new version is published on the gallery now.  thanks for all the help and info!
