### ISSUE TITLE
Outdated security components

### ISSUE THREAD

**Issue by powershellking** [dotps1/WinSCP#84]
When scanning the PowerShell-Module with Fortify, there are some critical vulnerabilities (see attachments)

[winscp-masterzip-vulnerabilities.csv.pdf](https://github.com/dotps1/WinSCP/files/2450678/winscp-masterzip-vulnerabilities.csv.pdf)
[winscp-masterzip-2018-10-05-130322.pdf.pdf](https://github.com/dotps1/WinSCP/files/2450679/winscp-masterzip-2018-10-05-130322.pdf.pdf)

**Comment by dotps1** [comment]
Please see the description of this repository
>WinSCP PowerShell Wrapper Module

Those vulnerabilities are with the `WinSCPNet.dll` and the `WinSCP.exe`.  I do not manage those assemblies, this is only a PowerShell module to interface with those assemblies.
