### ISSUE TITLE
Creating session trough SFTP with SSH key is no working - cannot define username

### ISSUE THREAD

**Issue by theLoFix** [dotps1/WinSCP#88]
### Issue Description

I'm trying to open session with generated SSH key, but when open session module is trying to connect as anonymous user. How can I defined name of the user I want to be logged to? addinf Credential option will pop out password prompt...

### Example

`
$sessionOptions = New-WinSCPSessionOption -HostName $Hostname -Protocol sftp -SshHostKeyFingerprint $SshHostKeyFingerprint -SshPrivateKeyPath $SshPrivateKeyPath -SecurePrivateKeyPassphrase $SecurePrivateKeyPassphrase
`
### Expected Output

Connection should be established via SSH key on defined user.

### Actual Output

```
New-WinSCPSession : Exception calling "Open" with "1" argument(s): "Connection has been unexpectedly closed. Server sent command exit status 0.
Authentication log (see session log for details):
Using username "anonymous".
Server refused our key.
Authentication failed."
At line:1 char:25
+ ...           $session = New-WinSCPSession -SessionOption $sessionOptions
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-WinSCPSession], MethodInvocationException
    + FullyQualifiedErrorId : SessionRemoteException,New-WinSCPSession
```
 

### WinSCP-PowerShell Version

```
ModuleType Version    Name                                ExportedCommands                                                                                                 
---------- -------    ----                                ----------------                                                                                                 
Script     0.0.0.0    WinSCP                              {ConvertTo-WinSCPEscapedString, Copy-WinSCPItem, Get-WinSCPChildItem, Get-WinSCPHostKeyFingerprint...}     
```      

### Environment

FTP:
SUSE Linux Enterprise Server 12 SP3

**Comment by dotps1** [comment]
I don't have anyway to test this, but your could try using the `-Credential` parameter.  and passing it a `[PSCredential]` object.  And you could try using a blank one as well `-Credential ( [PSCredential]::new())`.

**Comment by theLoFix** [comment]
Hello @dotps1.
I make a quick test of  passing Object of Type, with only a username:
`TypeName: System.Management.Automation.PSCredential`

And this works! 
I only used different action to create one:
`$cred = Get-Credential`
Code you suggested is form .Net I believe and it does not work on Power Shell, probably some Library is missing.
Never the less passing PSCredential object wit username only, and without password provided on credential prompt works like a charm. 
Thx for help.

**Comment by dotps1** [comment]
I wanted to suggest a few more ideas.
my mistake, to create an empty `PSCredential` object, this is the way to do so:
```powershell
[PSCredential]::Empty
```
You can also try to it like this to specify just a username:
```powershell
[PSCredential]::new( "userName", [SecureString]::new() )
```

but you can use either of those in the `-Credential` parameter to avoid the credential prompt.
