### ISSUE TITLE
[Request] Apply updates from 5.13.8, latest stable release

### ISSUE THREAD

**Issue by jeffreymcclain** [dotps1/WinSCP#90]
I noticed that the latest stable version of WinSCP is currently 5.13.8, whereas your module is still on 5.13.7. No rush or urgency to this request, just if you have some time it would be nice if you could sync the module to the latest version.

**Comment by dotps1** [comment]
ill get a new version published this week, however, after looking at the change log on winscp.net, I'm not seeing anything pressing to make a new version: https://winscp.net/eng/docs/history#5.13.8.  Ill close this when I push the new version.

thanks.

**Comment by dotps1** [comment]
5.13.8 is now published to the PowerShellGallery.
