### ISSUE TITLE
Documentation, Parameter "Position" should be "named" in most cases rather than an array index

### ISSUE THREAD

**Issue by jeffreymcclain** [dotps1/WinSCP#92]
### Issue Description

The documentation is a bit misleading, when the position for parameters is stated as "6", "7", "8", etc it implies the module won't work if those parameters are passed in any other order. However, from testing the parameters can be passed in any order as long as they are named.

### Example

https://github.com/dotps1/WinSCP/wiki/New-WinSCPSessionOption#parameters
https://github.com/dotps1/WinSCP/wiki/New-WinSCPTransferOption#parameters

### WinSCP-PowerShell Version

5.13.8

**Comment by dotps1** [comment]
ill be sure to remove those parameter position attributes.  thanks for pointing this out.

**Comment by dotps1** [comment]
I updated the help, but those `Position` attributes are being placed by the help files that are auto generated by `platyPS`.  the code itself does not have explicitly typed position attributes on the parameters.

https://github.com/dotps1/WinSCP/blob/master/WinSCP/Public/New-WinSCPTransferOption.ps1#L13

ill check with @vors and see what his thoughts are on that.

**Comment by dotps1** [comment]
So, this maybe a bigger `issue` (not sure this an issue really), but basically it appears that platyPS, which is used to generate this help, builds the data off what PowerShell is handing it, and it _should_ be handing a value of `Named` for all parameters.  But instead its auto number them based on the order the parameters are placed in the `Param` code block.  So I opened a ticked with the PowerShell team about this.

I personally would _Always_ recommend strongly typing your parameter names and values.  not only with this module, but with any module.  I don't explicitly support parameter position values in this module, despite what the auto generated help states.

**Comment by dotps1** [comment]
So, the PowerShell community has been chiming in very quickly on this, and it seems to be an issue with platyPS itself, so here is the new issue to watch,  https://github.com/PowerShell/platyPS/issues/454.

**Comment by dotps1** [comment]
Ok, I figured out what was going on with the auto generated help, and I have fixed it.  I have standardized all cmdlets to use the `PositionalBinding = $false` attribute.  The _only_ parameters that now support usage by position are `Path` and `Destination`.  I have updated the wiki as well.  I am not going to push a new version to the gallery for this, as nothing was really _broken_.

Thanks.
