### ISSUE TITLE
Get-WinSCPItemChecksum : Exception calling "CalculateFileChecksum" with "2" argument(s): "Operation not supported."

### ISSUE THREAD

**Issue by theLoFix** [dotps1/WinSCP#94]
_Please fill in the following fields, replacing the values inside the brackets `{{ }}`._

### Issue Description

When I'm trying to get remote file checksum, I got error:
`Get-WinSCPItemChecksum : Exception calling "CalculateFileChecksum" with "2" argument(s): "Operation not supported."`

_Connection is made via SCP protocol._

### Example

`$remoteFileHash = Get-WinSCPItemChecksum -WinSCPSession $session -Path $remoteFile -Algorithm sha1`

### Expected Output

Hash value of remote file based on SHA-1 Algorithm

### Actual Output

```
Get-WinSCPItemChecksum : Exception calling "CalculateFileChecksum" with "2" argument(s): "Operation not supported."
At line:1 char:35
+ ... eFileHash = Get-WinSCPItemChecksum -WinSCPSession $session -Path $rem ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WinSCPItemChecksum], MethodInvocationException
    + FullyQualifiedErrorId : SessionRemoteException,Get-WinSCPItemChecksum
```

### WinSCP-PowerShell Version

```
ModuleType Version    Name                                ExportedCommands                                                                           
---------- -------    ----                                ----------------                                                                           
Script     5.13.9.1   WinSCP                              {ConvertTo-WinSCPEscapedString, Copy-WinSCPItem, Get-WinSCPChildItem, Get-WinSCPHostKeyF...
```

### Environment
Script runs on:
Windows Server 2012 R2

Destination FTP: 
SUSE Linux Enterprise Server 12 SP3

**Comment by martinprikryl** [comment]
The method is not supported with SCP protocol:
https://winscp.net/eng/docs/protocols

On the other hand, with SCP you can call a command like `sha256sum <file>` using [`Invoke-WinSCPCommand`](https://github.com/dotps1/WinSCP/wiki/Invoke-WinSCPCommand).

**Comment by theLoFix** [comment]
I switch to SFTP, but it seems problem lays in protocol version on server side.
 Session output shows sth like this:
`Command 'checksum "sha-1" "/file.csv"'
failed with return code 127 and error message
-bash: line 15: checksum: command not found.`

It doeas not metter if i use _Get-WinSCPItemChecksum_ or _Invoke-WinSCPCommand_ becuse on the end they use the same WinSCP command. So I need to check it on server side. 
I just notice thet even  if I use WinSCP GUI this option is greyed out:
![image](https://user-images.githubusercontent.com/25254833/54918188-e1976a80-4efd-11e9-9e2f-d4a5df041700.png)


THX @martinprikryl

**Comment by martinprikryl** [comment]
SFTP won't usually help (I was not suggesting that), as most SFTP server does not support checksum feature (that's why the GUI dialog is disabled - if you dialog is from an SFTP session).

I've suggested you to use `sha256sum <file>` *shell* command, not `checksum "sha-1" <file>`.
