### ISSUE TITLE
Receive-WinSCPItem removes file from source by default in FTP connection

### ISSUE THREAD

**Issue by jeffreymcclain** [dotps1/WinSCP#95]
### Issue Description

Receive-WinSCPItem removes file from source during an FTP session, even if "-remove" parameter isn't specified (should default to false).

### Example

```
#connect using FTP
$sessionOption = New-WinSCPSessionOption -Credential $credential -FtpSecure 'Explicit' -HostName $hostName -PortNumber '20021' -Protocol 'FTP' -TlsHostCertificateFingerprint $fingerprint -RawSetting @{MinTlsVersion=12}

$session = New-WinSCPSession -SessionOption $sessionOption

Receive-WinSCPItem -WinSCPSession $session -RemotePath $source -LocalPath $destination -ErrorAction Stop
```

### Expected Output

File should still be present in source.

### Actual Output

File is no longer present in source.

### WinSCP-PowerShell Version

5.13.9

### Environment

PowerShell 5.1, Windows 10 v1809

**Comment by jeffreymcclain** [comment]
I'm not sure if the issue is with this module, or if the source server can somehow detect if the file has been copied and then removes it (not even sure if this is possible, and if so seems unlikely as that would be a very strange implementation on the source server's end).

**Comment by martinprikryl** [comment]
So did you test the behavior with any FTP client (like WinSCP GUI itself)?

**Comment by dotps1** [comment]
Can you try testing with the gui client?  You can take a look at the `Receive-WinSCPItem` cmdlet,  the `-Remove` parameter is of type `[Switch]` so its not exactly the same as a `[Bool]`.  So that allows me to call the `([Switch]$Remove).IsPresent()` method on it.  basically the parameter just has to be there.
https://github.com/dotps1/WinSCP/blob/0c025abef7eaad0b9a797dca9d790a823b08bb8d/WinSCP/Public/Receive-WinSCPItem.ps1#L67

so I'm not really sure its possible for the cmdlet itself to be doing that.

**Comment by jeffreymcclain** [comment]
> Can you try testing with the gui client? You can take a look at the `Receive-WinSCPItem` cmdlet, the `-Remove` parameter is of type `[Switch]` so its not exactly the same as a `[Bool]`. So that allows me to check the `([Switch]$Remove).IsPresent` property on it. basically the parameter just has to be there.
> [WinSCP/WinSCP/Public/Receive-WinSCPItem.ps1](https://github.com/dotps1/WinSCP/blob/0c025abef7eaad0b9a797dca9d790a823b08bb8d/WinSCP/Public/Receive-WinSCPItem.ps1#L67)
> 
> Line 67 in [0c025ab](/dotps1/WinSCP/commit/0c025abef7eaad0b9a797dca9d790a823b08bb8d)
> 
>  $remotePathValue, $LocalPath, $Remove.IsPresent, $TransferOptions 
> so I'm not really sure its possible for the cmdlet itself to be doing that.

So I just tried using the WinSCP GUI, when I attempt to drag and drop the file on the FTP connection the transfer settings dialog box never appears, the file is moved to my local directory but immediately removed from the source. When I use WinSCP GUI with an SFTP connection, it works as expected. 

So it seems like something is buggy with either WinSCP itself or this particular remote server using FTP, maybe something to do with the explicit TLS?

**Comment by martinprikryl** [comment]
Consider posting WinSCP session log file for the FTP session. Though I'm quite sure that it's simply a behavior (or a bug) of the FTP server.

**Comment by dotps1** [comment]
you can use the `-DebugLogPath` when calling `New-WinSCPSession` to output a log.

**Comment by martinprikryl** [comment]
Rather `-SessionLogPath`

**Comment by jeffreymcclain** [comment]
Well, I tried copy-pasting the file back to the remote server. Good news is I can still transfer it back out (copying now seems to work), but it keeps erroring out when I try to remove it from the source saying "permission denied." So idk what is happening, this file is gets added to the source server daily so hopefully tomorrow's file overwrites today's file as expected.

Is there a way to view the debug log from within the WinSCP GUI?

**Comment by dotps1** [comment]
maybe they have some scheduled task looking for the copy operation that then deletes the source so its clean for the next days file?

**Comment by jeffreymcclain** [comment]
> maybe they have some scheduled task looking for the copy operation that then deletes the source so its clean for the next days file?

Possibly, I don't know. I'm just hoping tomorrow's file from the source overwrites the one I drag and dropped onto the remote server, otherwise we're definitely gonna have issues :(
