### ISSUE TITLE
Apply updates from 5.15, latest stable release

### ISSUE THREAD

**Issue by jeffreymcclain** [dotps1/WinSCP#97]
### Issue Description

I noticed that the latest stable version of WinSCP is currently 5.15, whereas your module is still on 5.13.9.1. No rush or urgency to this request, just when you have some time it would be nice if you could sync the module to the latest version.

P.S.: I made a pull request for a small documentation fix last week, not sure if you saw it or if I did it properly. Again no rush, I'm sure you have more important things to work on.

**Comment by dotps1** [comment]
this one is going to take me a little bit, the `WinSCPnet.dll` is broken up into two files now.  So I have figure out how I want to handle that.  I merged your help updated.  thanks.
